# Generated by Django 5.2 on 2025-10-12 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del icono', max_length=50, null=True)),
                ('color', models.CharField(default='#00ffff', help_text='Color hexadecimal', max_length=7)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Área de Vida',
                'verbose_name_plural': 'Áreas de Vida',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Eudaimonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(choices=[('alta', 'Prioridad Alta'), ('media', 'Prioridad Media'), ('baja', 'Prioridad Baja')], default='media', max_length=5)),
                ('puntuacion', models.IntegerField(default=5, help_text='Puntuación del 1 al 10')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.areavida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eudaimonia_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eudaimonia',
                'verbose_name_plural': 'Eudaimonia',
                'unique_together': {('usuario', 'area')},
            },
        ),
        migrations.CreateModel(
            name='EventoKairos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('personal', 'Personal'), ('trabajo', 'Trabajo'), ('salud', 'Salud'), ('social', 'Social'), ('desarrollo', 'Desarrollo Personal'), ('otro', 'Otro')], default='personal', max_length=10)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('todo_el_dia', models.BooleanField(default=False)),
                ('recordatorio', models.BooleanField(default=False)),
                ('minutos_recordatorio', models.PositiveIntegerField(default=15, help_text='Minutos antes del evento')),
                ('completado', models.BooleanField(default=False)),
                ('color', models.CharField(default='#00ffff', help_text='Color hexadecimal', max_length=7)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_kairos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento Kairos',
                'verbose_name_plural': 'Eventos Kairos',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Gnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('podcast', 'Podcast'), ('video', 'Vídeo'), ('libro', 'Libro'), ('receta', 'Receta'), ('articulo', 'Artículo')], max_length=10)),
                ('estado', models.CharField(choices=[('finalizado', 'Finalizado'), ('en_progreso', 'En progreso'), ('no_empezado', 'No empezado')], default='no_empezado', max_length=12)),
                ('tematica', models.CharField(blank=True, max_length=100, null=True)),
                ('puntuacion', models.CharField(blank=True, choices=[('legendario', 'Legendario'), ('muy_bueno', 'Muy bueno'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10, null=True)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenido_gnosis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gnosis',
                'verbose_name_plural': 'Gnosis',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProsocheMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('año', models.IntegerField()),
                ('objetivo_mes_1', models.TextField(blank=True)),
                ('objetivo_mes_2', models.TextField(blank=True)),
                ('objetivo_mes_3', models.TextField(blank=True)),
                ('objetivo_mes_1_completado', models.BooleanField(default=False)),
                ('objetivo_mes_2_completado', models.BooleanField(default=False)),
                ('objetivo_mes_3_completado', models.BooleanField(default=False)),
                ('logro_principal', models.TextField(blank=True, help_text='Principal logro del mes y cómo lo he celebrado')),
                ('obstaculo_principal', models.TextField(blank=True, help_text='Principal obstáculo del mes y cómo lo he gestionado')),
                ('aprendizaje_principal', models.TextField(blank=True, help_text='Principal aprendizaje del mes')),
                ('momento_felicidad', models.TextField(blank=True, help_text='Principal momento de felicidad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-año', '-mes'],
                'unique_together': {('usuario', 'mes', 'año')},
            },
        ),
        migrations.CreateModel(
            name='ProsocheHabito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#00ffff', help_text='Color en formato hex', max_length=7)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('prosoche_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to='diario.prosochemes')),
            ],
            options={
                'unique_together': {('prosoche_mes', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='EjercicioArete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('instrucciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('sin_completar', 'Sin completar'), ('completado', 'Completado'), ('a_repetir', 'A repetir')], default='sin_completar', max_length=15)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('reflexiones', models.TextField(blank=True, null=True)),
                ('numero_orden', models.PositiveIntegerField(default=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_arete', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ejercicio Areté',
                'verbose_name_plural': 'Ejercicios Areté',
                'ordering': ['numero_orden'],
                'unique_together': {('usuario', 'numero_orden')},
            },
        ),
        migrations.CreateModel(
            name='EntrenamientoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(help_text='Fecha de inicio de la semana')),
                ('tipo', models.CharField(choices=[('pesas', 'Pesas'), ('cardio', 'Cardio'), ('movilidad', 'Movilidad')], max_length=10)),
                ('lunes', models.TextField(blank=True, null=True)),
                ('martes', models.TextField(blank=True, null=True)),
                ('miercoles', models.TextField(blank=True, null=True)),
                ('jueves', models.TextField(blank=True, null=True)),
                ('viernes', models.TextField(blank=True, null=True)),
                ('sabado', models.TextField(blank=True, null=True)),
                ('domingo', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenamientos_semanales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrenamiento Semanal',
                'verbose_name_plural': 'Entrenamientos Semanales',
                'ordering': ['-semana_inicio'],
                'unique_together': {('usuario', 'semana_inicio', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='PlanificacionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('actividad', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones_diarias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planificación Diaria',
                'verbose_name_plural': 'Planificaciones Diarias',
                'ordering': ['fecha', 'hora'],
                'unique_together': {('usuario', 'fecha', 'hora')},
            },
        ),
        migrations.CreateModel(
            name='ProsocheHabitoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)])),
                ('completado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='diario.prosochehabito')),
            ],
            options={
                'ordering': ['dia'],
                'unique_together': {('habito', 'dia')},
            },
        ),
        migrations.CreateModel(
            name='ProsocheDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('entrada', models.TextField(help_text='Entrada del diario')),
                ('estado_animo', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='Estado de ánimo (1-5)')),
                ('etiquetas', models.CharField(blank=True, help_text='Etiquetas separadas por comas', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('prosoche_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_diario', to='diario.prosochemes')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('prosoche_mes', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='ProsocheSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semana', models.IntegerField(choices=[(1, 'Semana 1'), (2, 'Semana 2'), (3, 'Semana 3'), (4, 'Semana 4'), (5, 'Semana 5')])),
                ('objetivo_1', models.TextField(blank=True)),
                ('objetivo_2', models.TextField(blank=True)),
                ('objetivo_3', models.TextField(blank=True)),
                ('objetivo_1_completado', models.BooleanField(default=False)),
                ('objetivo_2_completado', models.BooleanField(default=False)),
                ('objetivo_3_completado', models.BooleanField(default=False)),
                ('prosoche_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas', to='diario.prosochemes')),
            ],
            options={
                'ordering': ['numero_semana'],
                'unique_together': {('prosoche_mes', 'numero_semana')},
            },
        ),
        migrations.CreateModel(
            name='SeguimientoVires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grasa_corporal', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('masa_muscular', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('agua_corporal', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('entrenamiento_realizado', models.BooleanField(default=False)),
                ('descripcion_entrenamiento', models.TextField(blank=True, null=True)),
                ('alimentacion_saludable', models.BooleanField(default=False)),
                ('hidratacion_adecuada', models.BooleanField(default=False)),
                ('descanso_suficiente', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento_vires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento Vires',
                'verbose_name_plural': 'Seguimientos Vires',
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='TrimestreEudaimonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(help_text='Ejemplo: Q1 2025', max_length=20)),
                ('año', models.IntegerField(default=2025)),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('pausado', 'Pausado')], default='planificado', max_length=12)),
                ('objetivos', models.TextField(blank=True, null=True)),
                ('plan_accion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('resultados', models.TextField(blank=True, null=True)),
                ('eudaimonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimestres', to='diario.eudaimonia')),
            ],
            options={
                'verbose_name': 'Trimestre Eudaimonia',
                'verbose_name_plural': 'Trimestres Eudaimonia',
                'ordering': ['-año', '-trimestre'],
                'unique_together': {('eudaimonia', 'trimestre', 'año')},
            },
        ),
    ]
