# Generated by Django 5.2 on 2025-10-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prosochediario',
            name='entrada',
        ),
        migrations.AddField(
            model_name='prosochediario',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prosochediario',
            name='felicidad',
            field=models.TextField(blank=True, help_text='¿Qué me ha hecho feliz hoy?'),
        ),
        migrations.AddField(
            model_name='prosochediario',
            name='gratitud_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prosochediario',
            name='gratitud_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prosochediario',
            name='gratitud_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prosochediario',
            name='gratitud_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prosochediario',
            name='gratitud_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prosochediario',
            name='persona_quiero_ser',
            field=models.TextField(blank=True, help_text='¿Qué clase de persona quiero ser hoy?'),
        ),
        migrations.AddField(
            model_name='prosochediario',
            name='podcast_libro_dia',
            field=models.TextField(blank=True, help_text='Podcast o libro del día'),
        ),
        migrations.AddField(
            model_name='prosochediario',
            name='que_ha_ido_bien',
            field=models.TextField(blank=True, help_text='¿Qué ha ido bien?'),
        ),
        migrations.AddField(
            model_name='prosochediario',
            name='que_puedo_mejorar',
            field=models.TextField(blank=True, help_text='¿Qué puedo mejorar?'),
        ),
        migrations.AddField(
            model_name='prosochediario',
            name='reflexiones_dia',
            field=models.TextField(blank=True, help_text='Reflexiones del día'),
        ),
        migrations.AddField(
            model_name='prosochediario',
            name='tareas_dia',
            field=models.JSONField(blank=True, default=list, help_text='Lista de tareas del día con estado de completado'),
        ),
    ]
