# Generated by Django 5.2 on 2025-10-18 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_remove_prosochediario_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientovires',
            name='calidad_sueno',
            field=models.IntegerField(blank=True, help_text='Calidad del sueño (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='seguimientovires',
            name='horas_sueno',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas de sueño de la noche anterior', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='seguimientovires',
            name='nivel_energia',
            field=models.IntegerField(blank=True, help_text='Nivel de energía general (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='seguimientovires',
            name='nivel_estres',
            field=models.IntegerField(blank=True, help_text='Nivel de estrés percibido (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='seguimientovires',
            name='pasos',
            field=models.PositiveIntegerField(blank=True, help_text='Pasos totales del día', null=True),
        ),
    ]
