# Generated by Django 5.2 on 2025-10-18 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0003_seguimientovires_calidad_sueno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logro_principal', models.TextField(blank=True, help_text='El mayor logro de la semana.')),
                ('obstaculo_principal', models.TextField(blank=True, help_text='El mayor desafío enfrentado.')),
                ('aprendizaje_principal', models.TextField(blank=True, help_text='El aprendizaje más importante.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('semana', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='diario.prosochesemana')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
