# Generated by Django 5.2 on 2025-10-18 18:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0004_revisionsemanal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaImportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_relacion', models.CharField(choices=[('familia', 'Familia'), ('pareja', 'Pareja'), ('amigo', 'Amigo/a'), ('mentor', 'Mentor/a'), ('colega', 'Colega de Trabajo'), ('otro', 'Otro')], default='amigo', max_length=20)),
                ('salud_relacion', models.IntegerField(default=3, help_text='Salud percibida de la relación (1=Mala, 5=Excelente)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notas', models.TextField(blank=True, help_text='Notas generales sobre esta persona o relación.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='Describe la interacción. ¿Qué pasó?')),
                ('mi_sentir', models.TextField(blank=True, help_text='¿Cómo me sentí durante y después?')),
                ('aprendizaje', models.TextField(blank=True, help_text='¿Qué aprendí sobre mí mismo o sobre los demás?')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo_interaccion', models.CharField(choices=[('positiva', 'Positiva'), ('negativa', 'Negativa'), ('neutra', 'Neutra'), ('conflicto', 'Conflicto'), ('apoyo', 'Apoyo Recibido/Dado')], default='neutra', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('personas', models.ManyToManyField(blank=True, to='diario.personaimportante')),
            ],
        ),
    ]
