# Generated by Django 5.2 on 2025-10-19 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0005_personaimportante_interaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosochehabitodia',
            name='habito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_completados', to='diario.prosochehabito'),
        ),
    ]
