# Generated by Django 5.2 on 2025-10-23 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0006_alter_prosochehabitodia_habito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la insignia (ej: racha_7_dias)', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la insignia', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción de lo que representa')),
                ('virtud_asociada', models.CharField(choices=[('sabiduria', 'Sabiduría'), ('coraje', 'Coraje'), ('justicia', 'Justicia'), ('templanza', 'Templanza'), ('general', 'General')], default='general', max_length=20)),
                ('icono', models.CharField(default='fa-trophy', help_text='Icono Font Awesome', max_length=50)),
                ('color', models.CharField(default='#FFD700', help_text='Color en formato hex', max_length=7)),
                ('criterio_logro', models.TextField(help_text='Descripción de cómo se obtiene esta insignia')),
                ('puntos_virtud', models.IntegerField(default=0, help_text='Puntos de virtud que otorga al desbloquear')),
                ('es_secreta', models.BooleanField(default=False, help_text='Si es secreta, no se muestra hasta desbloquearla')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('activa', models.BooleanField(default=True)),
                ('veces_desbloqueada', models.IntegerField(default=0, help_text='Cuántos usuarios la han desbloqueado')),
            ],
            options={
                'verbose_name': 'Insignia',
                'verbose_name_plural': 'Insignias',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReflexionGuiadaTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la reflexión guiada', max_length=200)),
                ('slug', models.SlugField(help_text='Identificador único (ej: dia-mundial-ela)', unique=True)),
                ('fecha_activacion', models.DateField(help_text='¿Qué día se muestra esta reflexión?')),
                ('es_recurrente', models.BooleanField(default=True, help_text='¿Se repite cada año?')),
                ('activa', models.BooleanField(default=True, help_text='¿Está activa esta reflexión?')),
                ('contexto', models.TextField(help_text='Explicación breve del tema (2-3 párrafos)')),
                ('cita_filosofica', models.TextField(help_text='Cita relevante de un filósofo o pensador')),
                ('autor_cita', models.CharField(help_text='Autor de la cita', max_length=100)),
                ('pregunta_1', models.TextField(help_text='Primera pregunta para reflexionar')),
                ('pregunta_2', models.TextField(blank=True, help_text='Segunda pregunta (opcional)')),
                ('pregunta_3', models.TextField(blank=True, help_text='Tercera pregunta (opcional)')),
                ('pregunta_4', models.TextField(blank=True, help_text='Cuarta pregunta (opcional)')),
                ('pregunta_5', models.TextField(blank=True, help_text='Quinta pregunta (opcional)')),
                ('accion_sugerida', models.TextField(help_text='Acción concreta que el usuario puede hacer hoy')),
                ('categoria', models.CharField(choices=[('salud', 'Salud y Bienestar'), ('social', 'Causas Sociales'), ('filosofia', 'Filosofía y Pensamiento'), ('naturaleza', 'Naturaleza y Medio Ambiente'), ('personal', 'Desarrollo Personal'), ('historia', 'Historia y Cultura')], default='personal', max_length=20)),
                ('icono', models.CharField(default='fa-scroll', help_text='Icono Font Awesome', max_length=50)),
                ('color', models.CharField(default='#6c757d', help_text='Color en formato hex (ej: #3498db)', max_length=7)),
                ('veces_completada', models.IntegerField(default=0, help_text='Número de veces que usuarios han completado esta reflexión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reflexión Guiada (Tema)',
                'verbose_name_plural': 'Reflexiones Guiadas (Temas)',
                'ordering': ['fecha_activacion'],
            },
        ),
        migrations.CreateModel(
            name='RachaEscritura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_consecutivos', models.IntegerField(default=0, help_text='Días consecutivos escribiendo')),
                ('fecha_ultima_entrada', models.DateField(blank=True, help_text='Última fecha en que escribió', null=True)),
                ('racha_maxima', models.IntegerField(default=0, help_text='Racha más larga alcanzada')),
                ('fecha_racha_maxima', models.DateField(blank=True, help_text='Fecha en que alcanzó la racha máxima', null=True)),
                ('total_dias_escritos', models.IntegerField(default=0, help_text='Total de días que ha escrito (no necesariamente consecutivos)')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='racha_escritura', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Racha de Escritura',
                'verbose_name_plural': 'Rachas de Escritura',
            },
        ),
        migrations.CreateModel(
            name='ReflexionLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(blank=True, help_text='Título opcional de la reflexión', max_length=200)),
                ('contenido', models.TextField(help_text='Contenido de la reflexión')),
                ('etiquetas', models.CharField(blank=True, help_text='Etiquetas separadas por comas (ej: miedo,gratitud,decisión)', max_length=500)),
                ('tipo', models.CharField(choices=[('espontanea', 'Reflexión Espontánea'), ('guiada', 'Reflexión Guiada'), ('crisis', 'Reflexión de Apoyo')], default='espontanea', max_length=20)),
                ('estado_animo_post', models.IntegerField(blank=True, help_text='¿Cómo te sientes después de escribir? (1-5)', null=True)),
                ('es_privada', models.BooleanField(default=True, help_text='Si es privada, solo el usuario puede verla')),
                ('favorita', models.BooleanField(default=False, help_text='Marcar como favorita')),
                ('reflexion_guiada', models.ForeignKey(blank=True, help_text='Si es una reflexión guiada, referencia al tema', null=True, on_delete=django.db.models.deletion.SET_NULL, to='diario.reflexionguiadatema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflexiones_libres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reflexión Libre',
                'verbose_name_plural': 'Reflexiones Libres',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='InsigniaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtencion', models.DateTimeField(auto_now_add=True)),
                ('vista', models.BooleanField(default=False, help_text='¿El usuario ya vio la notificación de desbloqueo?')),
                ('favorita', models.BooleanField(default=False, help_text='¿El usuario la marcó como favorita?')),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_que_la_tienen', to='diario.insignia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias_desbloqueadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insignia de Usuario',
                'verbose_name_plural': 'Insignias de Usuarios',
                'ordering': ['-fecha_obtencion'],
                'unique_together': {('usuario', 'insignia')},
            },
        ),
        migrations.CreateModel(
            name='Virtud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sabiduria', 'Sabiduría (Sophia)'), ('coraje', 'Coraje (Andreia)'), ('justicia', 'Justicia (Dikaiosyne)'), ('templanza', 'Templanza (Sophrosyne)')], max_length=20)),
                ('puntos', models.IntegerField(default=0, help_text='Puntos acumulados en esta virtud')),
                ('nivel', models.CharField(choices=[('aprendiz', 'Aprendiz'), ('practicante', 'Practicante'), ('adepto', 'Adepto'), ('maestro', 'Maestro'), ('sabio', 'Sabio')], default='aprendiz', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_nivel', models.DateTimeField(auto_now_add=True, help_text='Fecha en que alcanzó el nivel actual')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Virtud',
                'verbose_name_plural': 'Virtudes',
                'unique_together': {('usuario', 'tipo')},
            },
        ),
    ]
