# Generated by Django 5.2 on 2026-01-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0007_insignia_reflexionguiadatema_rachaescritura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimestreeudaimonia',
            name='año',
            field=models.IntegerField(default=2026),
        ),
    ]
