# Generated by Django 5.2 on 2026-02-03 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0008_alter_trimestreeudaimonia_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosochehabito',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, default=datetime.date(2026, 2, 3), help_text='Fecha en que empezaste a trackear este hábito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prosochehabito',
            name='fecha_objetivo',
            field=models.DateField(blank=True, help_text='Fecha objetivo para completar el desafío', null=True),
        ),
        migrations.AddField(
            model_name='prosochehabito',
            name='objetivo_dias',
            field=models.IntegerField(default=30, help_text='Días objetivo para establecer/eliminar el hábito'),
        ),
        migrations.AddField(
            model_name='prosochehabito',
            name='tipo_habito',
            field=models.CharField(choices=[('positivo', 'Hábito a Formar'), ('negativo', 'Hábito a Eliminar')], default='positivo', help_text='¿Es un hábito que quieres formar o eliminar?', max_length=10),
        ),
    ]
