# Generated by Django 5.2 on 2026-02-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0009_prosochehabito_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosochehabito',
            name='anhelo_craving',
            field=models.CharField(blank=True, help_text="¿Qué deseas obtener? Ej: 'Sentirme energizado', 'Reducir ansiedad'", max_length=200, verbose_name='Anhelo (Craving)'),
        ),
        migrations.AddField(
            model_name='prosochehabito',
            name='identidad_objetivo',
            field=models.CharField(blank=True, help_text="¿Qué tipo de persona quieres ser? Ej: 'Soy una persona que cuida su salud'", max_length=200, verbose_name='Identidad Objetivo'),
        ),
        migrations.AddField(
            model_name='prosochehabito',
            name='ley_1_obvio',
            field=models.TextField(blank=True, help_text='¿Cómo harás este hábito obvio (positivo) o invisible (negativo)?', verbose_name='Ley 1: Hacerlo Obvio/Invisible'),
        ),
        migrations.AddField(
            model_name='prosochehabito',
            name='ley_2_atractivo',
            field=models.TextField(blank=True, help_text='¿Cómo harás este hábito atractivo (positivo) o no atractivo (negativo)?', verbose_name='Ley 2: Hacerlo Atractivo/No Atractivo'),
        ),
        migrations.AddField(
            model_name='prosochehabito',
            name='ley_3_facil',
            field=models.TextField(blank=True, help_text='¿Cómo harás este hábito fácil (positivo) o difícil (negativo)?', verbose_name='Ley 3: Hacerlo Fácil/Difícil'),
        ),
        migrations.AddField(
            model_name='prosochehabito',
            name='ley_4_satisfactorio',
            field=models.TextField(blank=True, help_text='¿Cómo harás este hábito satisfactorio (positivo) o insatisfactorio (negativo)?', verbose_name='Ley 4: Hacerlo Satisfactorio/Insatisfactorio'),
        ),
        migrations.AddField(
            model_name='prosochehabito',
            name='recompensa_reward',
            field=models.CharField(blank=True, help_text="¿Qué obtienes al hacerlo? Ej: 'Endorfinas', 'Sensación de logro'", max_length=200, verbose_name='Recompensa (Reward)'),
        ),
        migrations.AddField(
            model_name='prosochehabito',
            name='senal_cue',
            field=models.CharField(blank=True, help_text="¿Qué dispara este hábito? Ej: 'Después de despertarme', 'Cuando veo mi teléfono'", max_length=200, verbose_name='Señal (Cue)'),
        ),
    ]
