# Generated by Django 5.2 on 2026-02-03 19:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0010_prosochehabito_anhelo_craving_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerHabito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('emocion_previa', models.CharField(choices=[('estres', 'Estrés'), ('ansiedad', 'Ansiedad'), ('aburrimiento', 'Aburrimiento'), ('tristeza', 'Tristeza'), ('soledad', 'Soledad'), ('enojo', 'Enojo'), ('frustracion', 'Frustración'), ('cansancio', 'Cansancio'), ('euforia', 'Euforia'), ('otro', 'Otro')], help_text='¿Qué emoción sentías antes del impulso?', max_length=20, verbose_name='Emoción previa')),
                ('situacion', models.TextField(help_text='¿Qué estaba pasando? ¿Dónde estabas?', verbose_name='Situación')),
                ('personas_presentes', models.TextField(blank=True, help_text='¿Estabas solo o con alguien?', verbose_name='Personas presentes')),
                ('intensidad_deseo', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='¿Qué tan fuerte fue el impulso?', verbose_name='Intensidad del deseo (1-10)')),
                ('cediste', models.BooleanField(help_text='¿Recaíste o resististe el impulso?', verbose_name='¿Cediste?')),
                ('estrategia_usada', models.TextField(blank=True, help_text='¿Qué hiciste para resistir? (si resististe)', verbose_name='Estrategia usada')),
                ('aprendizaje', models.TextField(blank=True, help_text='¿Qué aprendiste de esta experiencia?', verbose_name='Aprendizaje')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('habito', models.ForeignKey(help_text='Hábito negativo al que pertenece este trigger', on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='diario.prosochehabito')),
            ],
            options={
                'verbose_name': 'Trigger de Hábito',
                'verbose_name_plural': 'Triggers de Hábitos',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
