# Generated by Django 5.2 on 2026-05-13 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0011_triggerhabito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaInterina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('sombra', 'En la Sombra'), ('radar', 'En el Radar de JOI'), ('promovida', 'Promovida a Simbiosis'), ('descartada', 'Descartada')], default='sombra', max_length=12)),
                ('veces_mencionada', models.PositiveIntegerField(default=1)),
                ('primera_deteccion', models.DateField(auto_now_add=True)),
                ('ultima_deteccion', models.DateField(auto_now=True)),
                ('persona_importante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origen_interino', to='diario.personaimportante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_interinas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona Interina',
                'verbose_name_plural': 'Personas Interinas',
                'ordering': ['-ultima_deteccion'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='InteraccionSombra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('mi_sentir', models.TextField(blank=True)),
                ('aprendizaje', models.TextField(blank=True)),
                ('tipo_interaccion', models.CharField(choices=[('positiva', 'Positiva'), ('negativa', 'Negativa'), ('neutra', 'Neutra'), ('conflicto', 'Conflicto'), ('apoyo', 'Apoyo')], default='neutra', max_length=12)),
                ('friccion_no', models.IntegerField(blank=True, help_text='Fricción del No registrada ese día', null=True)),
                ('persona_interina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='diario.personainterina')),
            ],
            options={
                'verbose_name': 'Interacción Sombra',
                'verbose_name_plural': 'Interacciones Sombra',
                'ordering': ['-fecha'],
            },
        ),
    ]
