# Generated by Django 5.2 on 2026-05-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0012_personainterina_interaccionsombra'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientovires',
            name='molestia_nota',
            field=models.TextField(blank=True, help_text='Nota libre sobre la molestia'),
        ),
        migrations.AddField(
            model_name='seguimientovires',
            name='molestia_zona',
            field=models.CharField(blank=True, choices=[('ninguna', 'Ninguna'), ('rodilla', 'Rodilla'), ('espalda', 'Espalda'), ('hombro', 'Hombro'), ('cuello', 'Cuello'), ('otra', 'Otra')], help_text='Zona corporal con molestia al empezar el día', max_length=50),
        ),
    ]
