# Generated by Django 5.2 on 2026-05-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0013_molestia_zona_vires'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientovires',
            name='cuerpo_cierre',
            field=models.CharField(blank=True, choices=[('ligero', 'Ligero'), ('cargado', 'Cargado'), ('dolorido', 'Dolorido'), ('apagado', 'Apagado')], help_text='Lectura corporal al cerrar el día', max_length=20),
        ),
    ]
