# Generated by Django 5.2 on 2026-05-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0014_cuerpo_cierre_vires'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosochediario',
            name='respuesta_joi_cierre',
            field=models.TextField(blank=True, help_text='Respuesta de JOI generada al cerrar el día'),
        ),
        migrations.AddField(
            model_name='prosochediario',
            name='respuesta_joi_cierre_generada_en',
            field=models.DateTimeField(blank=True, help_text='Timestamp de generación de la respuesta de cierre', null=True),
        ),
    ]
