# Generated by Django 5.2 on 2026-05-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0015_respuesta_joi_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='personainterina',
            name='menciones_desde_descarte',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
