# Generated by Django 5.2 on 2026-06-14 16:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0016_menciones_desde_descarte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('cultivo', 'Cultivo'), ('suelto', 'Suelto')], default='cultivo', max_length=10)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#00ffff', max_length=7)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('cerrado', 'Cerrado')], default='activo', max_length=10)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('periodo_observacion_dias', models.PositiveIntegerField(default=30)),
                ('mejor_racha', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['estado', 'nombre'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='RegistroGesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('cumplido', 'Cumplido'), ('fallado', 'Fallado')], default='cumplido', max_length=10)),
                ('nota', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('gesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='diario.gesto')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('gesto', 'fecha')},
            },
        ),
    ]
