# Generated by Django 5.2 on 2026-06-14 16:41

from datetime import date

from django.db import migrations


MESES_NUM = {
    # inglés (locale actual, LANGUAGE_CODE='en-us')
    'january': 1, 'february': 2, 'march': 3, 'april': 4, 'may': 5, 'june': 6,
    'july': 7, 'august': 8, 'september': 9, 'october': 10, 'november': 11, 'december': 12,
    # español (por si hay datos legacy en español)
    'enero': 1, 'febrero': 2, 'marzo': 3, 'abril': 4, 'mayo': 5, 'junio': 6,
    'julio': 7, 'agosto': 8, 'septiembre': 9, 'octubre': 10, 'noviembre': 11, 'diciembre': 12,
}


def mes_a_numero(nombre_mes):
    return MESES_NUM.get(nombre_mes.strip().lower())


def calcular_mejor_racha(fechas):
    """Devuelve la racha más larga de días consecutivos en un iterable de date."""
    fechas_ordenadas = sorted(set(fechas))
    if not fechas_ordenadas:
        return 0
    mejor = 1
    actual = 1
    for anterior, siguiente in zip(fechas_ordenadas, fechas_ordenadas[1:]):
        if (siguiente - anterior).days == 1:
            actual += 1
            mejor = max(mejor, actual)
        else:
            actual = 1
    return mejor


def migrar_datos(apps, schema_editor):
    ProsocheHabito = apps.get_model('diario', 'ProsocheHabito')
    Gesto = apps.get_model('diario', 'Gesto')
    RegistroGesto = apps.get_model('diario', 'RegistroGesto')

    grupos = {}
    for habito in ProsocheHabito.objects.select_related('prosoche_mes').all():
        usuario_id = habito.prosoche_mes.usuario_id
        nombre = habito.nombre.strip()
        clave = (usuario_id, nombre)
        grupos.setdefault(clave, []).append(habito)

    for (usuario_id, nombre), habitos in grupos.items():
        def orden_clave(h):
            mes_num = mes_a_numero(h.prosoche_mes.mes)
            if mes_num is None:
                print(
                    f"[migrar_habitos_a_gestos] Mes desconocido '{h.prosoche_mes.mes}' "
                    f"para habito '{h.nombre}' (usuario {usuario_id}); tratado como 0."
                )
                mes_num = 0
            return (h.prosoche_mes.año, mes_num)

        habitos_ordenados = sorted(habitos, key=orden_clave)
        mas_reciente = habitos_ordenados[-1]

        tipo = 'cultivo' if mas_reciente.tipo_habito == 'positivo' else 'suelto'
        objetivo_dias = mas_reciente.objetivo_dias or 30

        gesto, _ = Gesto.objects.get_or_create(
            usuario_id=usuario_id,
            nombre=nombre,
            defaults={
                'tipo': tipo,
                'color': mas_reciente.color,
                'periodo_observacion_dias': objetivo_dias,
            },
        )

        for habito in habitos_ordenados:
            mes_num = mes_a_numero(habito.prosoche_mes.mes)
            if mes_num is None:
                continue
            for dia in habito.dias_completados.filter(completado=True):
                try:
                    fecha = date(habito.prosoche_mes.año, mes_num, dia.dia)
                except ValueError:
                    print(
                        f"[migrar_habitos_a_gestos] Fecha invalida {habito.prosoche_mes.año}-"
                        f"{mes_num}-{dia.dia} para habito '{habito.nombre}' (usuario {usuario_id}); descartada."
                    )
                    continue
                RegistroGesto.objects.get_or_create(
                    gesto=gesto,
                    fecha=fecha,
                    defaults={'estado': 'cumplido'},
                )

        primer_registro = gesto.registros.order_by('fecha').first()
        if primer_registro:
            gesto.fecha_inicio = primer_registro.fecha
            gesto.save(update_fields=['fecha_inicio'])

        fechas_cumplidas = gesto.registros.filter(estado='cumplido').values_list('fecha', flat=True)
        mejor_racha_calculada = calcular_mejor_racha(fechas_cumplidas)
        if mejor_racha_calculada > gesto.mejor_racha:
            gesto.mejor_racha = mejor_racha_calculada
            gesto.save(update_fields=['mejor_racha'])


def reverse_migrar_datos(apps, schema_editor):
    RegistroGesto = apps.get_model('diario', 'RegistroGesto')
    Gesto = apps.get_model('diario', 'Gesto')

    RegistroGesto.objects.all().delete()
    Gesto.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0017_gesto_registrogesto'),
    ]

    operations = [
        migrations.RunPython(migrar_datos, reverse_migrar_datos),
    ]
