# Generated by Django 5.2 on 2026-06-14 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0018_migrar_habitos_a_gestos'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerhabito',
            name='gesto',
            field=models.ForeignKey(blank=True, help_text='Gesto al que pertenece este trigger (Phase 2.0D)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='diario.gesto'),
        ),
        migrations.AlterField(
            model_name='triggerhabito',
            name='habito',
            field=models.ForeignKey(blank=True, help_text='Hábito negativo legacy al que pertenece este trigger (Phase 2.0D: sustituido por gesto)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='diario.prosochehabito'),
        ),
    ]
