# Generated by Django 5.2 on 2026-07-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0020_backfill_triggerhabito_gesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosochediario',
            name='cierre_confirmado_en',
            field=models.DateTimeField(blank=True, help_text='Momento en que el núcleo del cierre diario quedó persistido con éxito', null=True),
        ),
    ]
