# Generated by Django 5.2 on 2026-07-18 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0021_prosochediario_cierre_confirmado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='gesto',
            name='cadencia_configurada_en',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gesto',
            name='dias_semana_objetivo',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gesto',
            name='frecuencia_semanal_objetivo',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gesto',
            name='tipo_cadencia',
            field=models.CharField(choices=[('libre', 'Sin objetivo fijo'), ('diaria', 'Todos los días'), ('semanal', 'Veces por semana'), ('dias_concretos', 'Días concretos')], default='libre', max_length=20),
        ),
        migrations.CreateModel(
            name='PausaGesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('gesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pausas', to='diario.gesto')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('fecha_fin__isnull', True)), fields=('gesto',), name='pausagesto_una_abierta_por_gesto')],
            },
        ),
    ]
