# Generated by Django 5.2 on 2026-07-18 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0022_gesto_cadencia_configurada_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gesto',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
