# Generated by Django 5.2 on 2026-08-01 19:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0025_cierre_nocturno_idempotente'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaccion',
            name='origen_sombra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaccion_migrada', to='diario.interaccionsombra'),
        ),
        migrations.AlterField(
            model_name='interaccionsombra',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
