# Generated by Django 5.2 on 2026-08-08 16:01

import django.db.models.deletion
import uuid
import unicodedata
from django.conf import settings
from django.db import migrations, models


def backfill_identidad_y_alias(apps, schema_editor):
    PersonaImportante = apps.get_model('diario', 'PersonaImportante')
    PersonaInterina = apps.get_model('diario', 'PersonaInterina')
    AliasSimbiosis = apps.get_model('diario', 'AliasSimbiosis')

    def normalizar(nombre):
        return ' '.join(unicodedata.normalize('NFKC', nombre or '').split()).casefold()

    for campo, modelo in (
        ('persona_confirmada', PersonaImportante),
        ('persona_interina', PersonaInterina),
    ):
        for entidad in modelo.objects.all().iterator():
            clave = normalizar(entidad.nombre)
            modelo.objects.filter(pk=entidad.pk).update(nombre_normalizado=clave)
            AliasSimbiosis.objects.create(
                usuario_id=entidad.usuario_id,
                nombre=entidad.nombre,
                nombre_normalizado=clave,
                origen='backfill',
                **{f'{campo}_id': entidad.pk},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0029_alter_personainterina_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personaimportante',
            name='fusionada_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identidades_fusionadas', to='diario.personaimportante'),
        ),
        migrations.AddField(
            model_name='personaimportante',
            name='nombre_normalizado',
            field=models.CharField(db_index=True, default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='personaimportante',
            name='tipo_entidad',
            field=models.CharField(choices=[('sin_clasificar', 'Sin clasificar'), ('persona', 'Persona'), ('grupo', 'Grupo')], default='sin_clasificar', max_length=16),
        ),
        migrations.AddField(
            model_name='personainterina',
            name='nombre_normalizado',
            field=models.CharField(db_index=True, default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='personainterina',
            name='tipo_entidad',
            field=models.CharField(choices=[('sin_clasificar', 'Sin clasificar'), ('persona', 'Persona'), ('grupo', 'Grupo')], default='sin_clasificar', max_length=16),
        ),
        migrations.CreateModel(
            name='OperacionIdentidadSimbiosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('corregir', 'Corregir identidad'), ('fusionar', 'Fusionar identidades'), ('deshacer', 'Deshacer operación')], max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('deshace_a', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operacion_deshacer', to='diario.operacionidentidadsimbiosis')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_identidad_destino', to='diario.personaimportante')),
                ('interina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_identidad', to='diario.personainterina')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_identidad_origen', to='diario.personaimportante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_identidad_simbiosis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AliasSimbiosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_normalizado', models.CharField(db_index=True, editable=False, max_length=100)),
                ('origen', models.CharField(default='manual', max_length=24)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('persona_confirmada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_simbiosis', to='diario.personaimportante')),
                ('persona_interina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_simbiosis', to='diario.personainterina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_simbiosis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('persona_confirmada__isnull', False), ('persona_interina__isnull', True)), models.Q(('persona_confirmada__isnull', True), ('persona_interina__isnull', False)), _connector='OR'), name='alias_simbiosis_exactamente_un_objetivo'), models.UniqueConstraint(fields=('usuario', 'persona_confirmada', 'nombre_normalizado'), name='alias_simbiosis_confirmada_normalizado_unico'), models.UniqueConstraint(fields=('usuario', 'persona_interina', 'nombre_normalizado'), name='alias_simbiosis_interina_normalizado_unico')],
            },
        ),
        migrations.RunPython(backfill_identidad_y_alias, migrations.RunPython.noop),
    ]
