# Generated by Django 5.2 on 2026-03-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejerciciobase',
            name='risk_tags',
            field=models.JSONField(blank=True, default=list, help_text="Tokens de riesgo, ej: 'impacto_vertical', 'triple_extension_explosiva'"),
        ),
    ]
