# Generated by Django 5.2 on 2026-09-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0003_ejerciciobase_tipo_progresion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejerciciobase',
            name='tipo_carga_default',
            field=models.CharField(choices=[('total', 'Peso total'), ('por_mano', 'Por mano'), ('por_lado', 'Por lado')], default='total', help_text='Cómo debe interpretar la interfaz el peso escrito por el usuario.', max_length=10),
        ),
    ]
