# Generated by Django 5.2 on 2026-09-15 17:17

from django.db import migrations, models


def configurar_incremento_barras(apps, schema_editor):
    EjercicioBase = apps.get_model('rutinas', 'EjercicioBase')
    EjercicioBase.objects.filter(nombre__icontains='barra').update(incremento_kg=4)


def restaurar_incremento_barras(apps, schema_editor):
    EjercicioBase = apps.get_model('rutinas', 'EjercicioBase')
    EjercicioBase.objects.filter(nombre__icontains='barra').update(incremento_kg=2.5)


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0004_ejerciciobase_tipo_carga_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejerciciobase',
            name='incremento_kg',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='Salto real disponible para los controles de carga (p. ej. 4 kg).', max_digits=5),
        ),
        migrations.RunPython(configurar_incremento_barras, restaurar_incremento_barras),
    ]
