# Generated by Django 5.2 on 2026-02-22 10:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_fasecliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='HyroxObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('open_men', 'Open Men'), ('open_women', 'Open Women'), ('pro_men', 'Pro Men'), ('pro_women', 'Pro Women'), ('doubles_men', 'Doubles Men'), ('doubles_women', 'Doubles Women'), ('doubles_mixed', 'Doubles Mixed'), ('relay', 'Relay')], default='open_men', max_length=20)),
                ('fecha_evento', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('rm_peso_muerto', models.FloatField(blank=True, help_text='kg', null=True)),
                ('rm_sentadilla', models.FloatField(blank=True, help_text='kg', null=True)),
                ('tiempo_5k_base', models.CharField(blank=True, help_text='formato MM:SS', max_length=10, null=True)),
                ('material_disponible', models.TextField(blank=True, help_text='Material del que dispone el usuario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyrox_objectives', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='HyroxSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('completado', 'Completado'), ('saltado', 'Saltado')], default='planificado', max_length=20)),
                ('tiempo_total_minutos', models.IntegerField(blank=True, null=True)),
                ('hr_media', models.IntegerField(blank=True, help_text='Frecuencia Cardíaca Media (lpm)', null=True)),
                ('hr_maxima', models.IntegerField(blank=True, help_text='Frecuencia Cardíaca Máxima (lpm)', null=True)),
                ('rpe_global', models.PositiveSmallIntegerField(blank=True, help_text='Escala de Esfuerzo Percibido 1-10', null=True)),
                ('notas_raw', models.TextField(blank=True, help_text='Texto libre pegado por el usuario del entrenamiento', null=True)),
                ('parsed_by_ia', models.BooleanField(default=False, help_text='True si ya fue procesado por el parser de IA')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='hyrox.hyroxobjective')),
            ],
        ),
        migrations.CreateModel(
            name='HyroxActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('fuerza', 'Fuerza / Musculación'), ('carrera', 'Carrera / Running'), ('ergometro', 'Ergómetro (Remo, SkiErg)'), ('isometrico', 'Isométricos (Wall Sit, Plancha)'), ('hyrox_station', 'Estación Específica Hyrox (Sled, Sandbag, etc.)'), ('otro', 'Otro / Mixto')], default='fuerza', max_length=25)),
                ('nombre_ejercicio', models.CharField(max_length=150)),
                ('data_metricas', models.JSONField(default=dict, help_text='JSON flexible con series, kg, tiempos, ritmos o FC extrados del texto libre')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='hyrox.hyroxsession')),
            ],
        ),
    ]
