# Generated by Django 5.2 on 2026-02-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyrox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyroxsession',
            name='feedback_ia',
            field=models.TextField(blank=True, help_text='Análisis y feedback del entrenador generado por IA', null=True),
        ),
    ]
