# Generated by Django 5.2 on 2026-02-22 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyrox', '0002_hyroxsession_feedback_ia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HyroxReadinessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_logs', to='hyrox.hyroxobjective')),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('objective', 'fecha')},
            },
        ),
    ]
