# Generated by Django 5.2 on 2026-02-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyrox', '0004_hyroxsession_ai_evaluation_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyroxobjective',
            name='lesiones_previas',
            field=models.TextField(blank=True, help_text='Ej: Rodilla derecha, lumbalgia. Dejar en blanco si no hay.'),
        ),
        migrations.AddField(
            model_name='hyroxobjective',
            name='nivel_experiencia',
            field=models.CharField(choices=[('principiante', 'Principiante (0-1 año)'), ('intermedio', 'Intermedio (1-3 años)'), ('avanzado', 'Avanzado (+3 años)')], default='intermedio', help_text='Experiencia en fuerza/cardio', max_length=20),
        ),
    ]
