# Generated by Django 5.2 on 2026-02-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyrox', '0005_hyroxobjective_lesiones_previas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyroxobjective',
            name='dias_preferidos',
            field=models.CharField(default='0,2,4,5', help_text='Días de la semana preferidos para entrenar (0=Lunes, 6=Domingo)', max_length=20),
        ),
    ]
