# Generated by Django 5.2 on 2026-02-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyrox', '0006_hyroxobjective_dias_preferidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyroxsession',
            name='nivel_energia_pre',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Energía reportada por el usuario hoy (1-10)', null=True),
        ),
    ]
