# Generated by Django 5.2 on 2026-03-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyrox', '0007_hyroxsession_nivel_energia_pre'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyroxsession',
            name='fatiga_updated_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se inyectó la fatiga por última vez (para Fatigue Decay)', null=True),
        ),
    ]
