# Generated by Django 5.2 on 2026-03-01 10:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_fasecliente'),
        ('hyrox', '0008_hyroxsession_fatiga_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInjury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_afectada', models.CharField(help_text='Ej: Gemelo derecho, Rodilla izquierda', max_length=100)),
                ('fase', models.CharField(choices=[('AGUDA', 'Fase Aguda (Alta inflamación, reposo relativo)'), ('SUB_AGUDA', 'Fase Sub-aguda (Movilidad sin dolor, carga parcial)'), ('RETORNO', 'Fase de Retorno (Fuerza excéntrica, carga progresiva)')], default='AGUDA', max_length=20)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('gravedad', models.IntegerField(default=5, help_text='Del 1 al 10')),
                ('activa', models.BooleanField(default=True)),
                ('tags_restringidos', models.JSONField(blank=True, default=list, help_text="Lista de Risk Tags prohibidos (ej. 'impacto_vertical', 'triple_extension_explosiva')")),
                ('notas_medicas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesiones_hyrox', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Registro de Lesión',
                'verbose_name_plural': 'Registros de Lesiones',
                'ordering': ['-activa', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DailyRecoveryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('dolor_reposo', models.IntegerField(default=0, help_text='0-10: Dolor sin hacer nada')),
                ('dolor_movimiento', models.IntegerField(default=0, help_text='0-10: Dolor al caminar o rango articular')),
                ('inflamacion_percibida', models.IntegerField(default=1, help_text='1-5: Hinchazón visual o palpación')),
                ('rango_movimiento', models.CharField(choices=[('LIMITADO', 'Movimiento limitado o doloroso'), ('NORMAL', 'Rango completo sin dolor significativo')], default='LIMITADO', max_length=15)),
                ('notas_usuario', models.TextField(blank=True, help_text='¿Tomaste AINEs hoy? ¿Aplicaste hielo?', null=True)),
                ('lesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to='hyrox.userinjury')),
            ],
            options={
                'verbose_name': 'Registro Diario de Recuperación',
                'verbose_name_plural': 'Registros Diarios de Recuperación',
                'ordering': ['-fecha'],
                'unique_together': {('lesion', 'fecha')},
            },
        ),
    ]
