# Generated by Django 5.2 on 2026-03-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyrox', '0009_userinjury_dailyrecoveryentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecoveryentry',
            name='inflamacion_percibida',
            field=models.IntegerField(default=1, help_text='1-10: 1=Sin hinchazón, 10=Inflamación severa'),
        ),
        migrations.AlterField(
            model_name='dailyrecoveryentry',
            name='rango_movimiento',
            field=models.IntegerField(default=5, help_text='1-10: 1=Muy limitado, 10=Rango completo normal'),
        ),
    ]
