# Generated by Django 5.2 on 2026-03-08 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyrox', '0010_alter_dailyrecoveryentry_inflamacion_percibida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinjury',
            name='fase',
            field=models.CharField(choices=[('AGUDA', 'Fase Aguda (Alta inflamación, reposo relativo)'), ('SUB_AGUDA', 'Fase Sub-aguda (Movilidad sin dolor, carga parcial)'), ('RETORNO', 'Fase de Retorno (Fuerza excéntrica, carga progresiva)'), ('RECUPERADO', 'Recuperado (Alta médica, sin restricciones)')], default='AGUDA', max_length=20),
        ),
        migrations.CreateModel(
            name='RecoveryTestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dolor_movimiento', models.PositiveSmallIntegerField(help_text='Dolor del 0 al 10')),
                ('inflamacion_percibida', models.PositiveSmallIntegerField(help_text='Inflamación percibida del 0 al 10')),
                ('confianza_atleta', models.PositiveSmallIntegerField(help_text='Confianza del atleta del 0 al 10')),
                ('es_apto', models.BooleanField(default=False)),
                ('lesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_tests', to='hyrox.userinjury')),
            ],
        ),
    ]
