# Generated by Django 5.2 on 2026-03-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyrox', '0011_alter_userinjury_fase_recoverytestlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hyroxsession',
            name='feedback_ia',
        ),
        migrations.AddField(
            model_name='hyroxsession',
            name='hubo_molestias',
            field=models.BooleanField(default=False, help_text='¿Hubo molestias en la lesión durante el entrenamiento?'),
        ),
    ]
