# Generated by Django 5.2 on 2026-04-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyrox', '0012_remove_hyroxsession_feedback_ia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyroxactivity',
            name='tipo_actividad',
            field=models.CharField(choices=[('fuerza', 'Fuerza / Musculación'), ('carrera', 'Carrera / Running'), ('ergometro', 'Ergómetro (Remo, SkiErg)'), ('isometrico', 'Isométricos (Wall Sit, Plancha)'), ('hyrox_station', 'Estación Específica Hyrox (Sled, Sandbag, etc.)'), ('cardio_sustituto', 'Cardio Sustituto (Fútbol, Ciclismo, etc.)'), ('hiit', 'HIIT / Interválico'), ('remo', 'Remo (Rowing Machine)'), ('skierg', 'SkiErg'), ('bici', 'Bicicleta / Ciclismo'), ('otro', 'Otro / Mixto')], default='fuerza', max_length=25),
        ),
    ]
