# Generated by Django 5.2 on 2026-04-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyrox', '0013_alter_hyroxactivity_tipo_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyroxobjective',
            name='fc_max_real',
            field=models.IntegerField(blank=True, help_text='FC máxima real medida en prueba de esfuerzo (lpm). Vacío = 220-edad.', null=True),
        ),
        migrations.AddField(
            model_name='hyroxobjective',
            name='fc_reposo',
            field=models.IntegerField(blank=True, default=60, help_text='FC en reposo por la mañana (lpm). Necesario para TRIMP Karvonen.', null=True),
        ),
        migrations.AddField(
            model_name='hyroxobjective',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', help_text='Factor b del TRIMP: M=1.92, F=1.67', max_length=1),
        ),
        migrations.AddField(
            model_name='hyroxsession',
            name='atl',
            field=models.FloatField(blank=True, help_text='Acute Training Load: fatiga acumulada (7 días, exponential decay)', null=True),
        ),
        migrations.AddField(
            model_name='hyroxsession',
            name='ctl',
            field=models.FloatField(blank=True, help_text='Chronic Training Load: fitness acumulado (42 días, exponential decay)', null=True),
        ),
        migrations.AddField(
            model_name='hyroxsession',
            name='trimp',
            field=models.FloatField(blank=True, help_text='Training Impulse (Banister): carga objetiva de la sesión', null=True),
        ),
        migrations.AddField(
            model_name='hyroxsession',
            name='tsb',
            field=models.FloatField(blank=True, help_text='Training Stress Balance: CTL - ATL (positivo=fresco, negativo=fatigado)', null=True),
        ),
        migrations.AddField(
            model_name='hyroxsession',
            name='zona_cardiaca_predominante',
            field=models.CharField(blank=True, help_text='Zona cardíaca predominante de la sesión: Z1-Z5', max_length=5, null=True),
        ),
    ]
