# Generated by Django 5.2 on 2026-04-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyrox', '0014_hyroxobjective_fc_max_real_hyroxobjective_fc_reposo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyroxactivity',
            name='data_planificado',
            field=models.JSONField(blank=True, help_text='Copia de data_metricas planificado antes de sobrescribir con lo real', null=True),
        ),
        migrations.AddField(
            model_name='hyroxsession',
            name='cumplimiento_ratio',
            field=models.FloatField(blank=True, help_text='0-1: qué % del volumen/distancia planificado completó el usuario', null=True),
        ),
    ]
