# Generated by Django 5.2 on 2026-04-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyrox', '0015_add_cumplimiento_y_data_planificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyroxreadinesslog',
            name='calidad_sueno',
            field=models.IntegerField(blank=True, help_text='Calidad subjetiva del sueño (1-10)', null=True),
        ),
        migrations.AddField(
            model_name='hyroxreadinesslog',
            name='fc_reposo',
            field=models.IntegerField(blank=True, help_text='FC de reposo al despertar (lpm) — indicador clave de recuperación', null=True),
        ),
        migrations.AddField(
            model_name='hyroxreadinesslog',
            name='horas_sueno',
            field=models.FloatField(blank=True, help_text='Horas de sueño la noche anterior', null=True),
        ),
    ]
