# Generated by Django 5.2 on 2026-04-26 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_strava_models'),
        ('hyrox', '0016_readiness_biometria_matutina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyroxobjective',
            name='dias_preferidos',
            field=models.CharField(default='0,2,4,6', help_text='Días de la semana preferidos para entrenar (0=Lunes, 6=Domingo)', max_length=20),
        ),
        migrations.CreateModel(
            name='StravaActivityRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.BigIntegerField(unique=True)),
                ('fecha_actividad', models.DateField()),
                ('tipo_strava', models.CharField(blank=True, max_length=50)),
                ('nombre_strava', models.CharField(blank=True, max_length=200)),
                ('duracion_segundos', models.IntegerField(default=0)),
                ('hr_media', models.IntegerField(blank=True, null=True)),
                ('hr_maxima', models.IntegerField(blank=True, null=True)),
                ('distancia_metros', models.FloatField(blank=True, null=True)),
                ('raw_json', models.JSONField()),
                ('estado', models.CharField(choices=[('pending', 'Pendiente de revisión'), ('merged', 'Fusionado con sesión existente'), ('created', 'Nueva sesión creada'), ('ignored', 'Ignorado por el usuario')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strava_activities', to='clientes.cliente')),
                ('hyrox_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strava_sources', to='hyrox.hyroxsession')),
            ],
            options={
                'verbose_name': 'Actividad Strava',
                'verbose_name_plural': 'Actividades Strava',
                'ordering': ['-fecha_actividad'],
            },
        ),
        migrations.CreateModel(
            name='StravaToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_id', models.BigIntegerField(unique=True)),
                ('access_token', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=200)),
                ('expires_at', models.DateTimeField()),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strava_token', to='clientes.cliente')),
            ],
        ),
    ]
