# Generated by Django 5.2 on 2026-04-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyrox', '0017_strava_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyroxobjective',
            name='objetivo_tiempo_carrera',
            field=models.CharField(blank=True, help_text='Tiempo objetivo para acabar la carrera (H:MM:SS o MM:SS)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hyroxobjective',
            name='peso_corporal',
            field=models.FloatField(blank=True, help_text='Peso corporal en kg (para escalar cargas relativas)', null=True),
        ),
        migrations.AddField(
            model_name='hyroxobjective',
            name='primer_hyrox',
            field=models.BooleanField(default=True, help_text='¿Es la primera vez que compite en Hyrox?'),
        ),
    ]
