# Generated by Django 5.2 on 2026-04-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyrox', '0018_objetivo_tiempo_peso_primer_hyrox'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyroxsession',
            name='station_feedback',
            field=models.JSONField(blank=True, help_text='Feedback por estación al final del entreno: [{estacion, pausas, fallos, sensacion}]', null=True),
        ),
    ]
