# Generated by Django 5.2 on 2026-04-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyrox', '0020_readinesslog_tiempo_estimado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hyroxreadinesslog',
            name='tiempo_estimado_seg',
        ),
    ]
