# Generated by Django 5.2 on 2026-05-09 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0016_actividad_hr_media_hr_maxima_strava'),
        ('hyrox', '0021_remove_hyroxreadinesslog_tiempo_estimado_seg'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaactivityraw',
            name='entreno_gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strava_sources', to='entrenos.entrenorealizado'),
        ),
    ]
