# Generated by Django 5.2 on 2026-05-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyrox', '0022_stravaactivityraw_entreno_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyroxreadinesslog',
            name='hrv_ms',
            field=models.PositiveSmallIntegerField(blank=True, help_text='HRV al despertar en ms (de BitacoraDiaria)', null=True),
        ),
    ]
