# Generated by Django 5.2 on 2026-05-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyrox', '0023_add_hrv_ms_to_readiness_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyroxobjective',
            name='objetivo_tiempo_total',
            field=models.CharField(blank=True, help_text='Objetivo personal de tiempo total HYROX completo. Ej: 1:40:00. No confundir con objetivo de carrera parcial.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hyroxobjective',
            name='objetivo_tiempo_carrera',
            field=models.CharField(blank=True, help_text='Tiempo objetivo para la carrera parcial (H:MM:SS o MM:SS)', max_length=10, null=True),
        ),
    ]
