# Generated by Django 5.2 on 2026-08-16 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0044_gymdecisionlog_molestia_reciente'),
        ('hyrox', '0024_add_objetivo_tiempo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaactivityraw',
            name='actividad_hub',
            field=models.OneToOneField(blank=True, help_text='Evento físico canónico enriquecido o creado desde esta actividad.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strava_source', to='entrenos.actividadrealizada'),
        ),
    ]
