# Generated by Django 5.2 on 2026-08-02 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0009_add_hrv_ms_to_bitacora'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioRehab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('tipo_contraccion', models.CharField(choices=[('isometrico', 'Isométrico'), ('isotonico_lento', 'Isotónico lento'), ('pliometrico', 'Pliométrico'), ('movilidad', 'Movilidad')], max_length=20)),
                ('descripcion_ejecucion', models.TextField()),
                ('equipo', models.CharField(blank=True, max_length=150)),
                ('nombre_equivalente_gym', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaseProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('slug', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=150)),
                ('objetivo', models.TextField()),
                ('duracion_minima_dias', models.PositiveIntegerField()),
                ('duracion_tipica_dias', models.PositiveIntegerField()),
                ('reglas_avance', models.JSONField(default=dict)),
                ('reglas_retroceso', models.JSONField(default=dict)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrescripcionEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('series', models.PositiveIntegerField()),
                ('frecuencia_semanal', models.PositiveIntegerField()),
                ('parametros', models.JSONField(default=dict)),
                ('notas', models.TextField(blank=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rehab.ejerciciorehab')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescripciones', to='rehab.faseprotocolo')),
            ],
        ),
        migrations.CreateModel(
            name='ProtocoloRehab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('version', models.IntegerField()),
                ('nombre', models.CharField(max_length=150)),
                ('zona', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fuente_referencia', models.TextField()),
                ('criterios_alta', models.JSONField(default=dict)),
                ('advertencias', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('slug', 'version')},
            },
        ),
        migrations.AddField(
            model_name='faseprotocolo',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='rehab.protocolorehab'),
        ),
        migrations.CreateModel(
            name='EpisodioRehab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo_version', models.IntegerField()),
                ('lateralidad', models.CharField(choices=[('izquierda', 'Izquierda'), ('derecha', 'Derecha'), ('bilateral', 'Bilateral')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fase_actual_desde', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PAUSADO', 'Pausado'), ('ALTA', 'Alta'), ('ABANDONADO', 'Abandonado')], default='ACTIVO', max_length=20)),
                ('dolor_basal_inicial', models.PositiveSmallIntegerField()),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios_rehab', to='clientes.cliente')),
                ('fase_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodios_en_curso', to='rehab.faseprotocolo')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='rehab.protocolorehab')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDiarioRehab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dolor_manana', models.PositiveSmallIntegerField()),
                ('rigidez_manana', models.PositiveSmallIntegerField()),
                ('notas', models.TextField(blank=True)),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to='rehab.episodiorehab')),
            ],
        ),
        migrations.CreateModel(
            name='SesionRehab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('COMPLETADA', 'Completada'), ('PARCIAL', 'Parcial'), ('OMITIDA', 'Omitida')], max_length=20)),
                ('dolor_durante', models.PositiveSmallIntegerField()),
                ('dolor_post_24h', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duracion_min', models.PositiveIntegerField(blank=True, null=True)),
                ('prescripcion_snapshot', models.JSONField(default=dict)),
                ('notas', models.TextField(blank=True)),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='rehab.episodiorehab')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='rehab.faseprotocolo')),
            ],
        ),
        migrations.CreateModel(
            name='EjercicioSesionRehab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_completadas', models.PositiveIntegerField()),
                ('carga_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dolor_ejercicio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('prescripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rehab.prescripcionejercicio')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='rehab.sesionrehab')),
            ],
        ),
        migrations.CreateModel(
            name='TransicionFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('direccion', models.CharField(choices=[('INICIO', 'Inicio'), ('AVANCE', 'Avance'), ('RETROCESO', 'Retroceso'), ('ALTA', 'Alta')], max_length=20)),
                ('motivo', models.CharField(max_length=100)),
                ('automatica', models.BooleanField()),
                ('evidencia', models.JSONField(default=dict)),
                ('confirmada_por_usuario', models.BooleanField(default=False)),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transiciones', to='rehab.episodiorehab')),
                ('fase_desde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transiciones_salida', to='rehab.faseprotocolo')),
                ('fase_hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transiciones_entrada', to='rehab.faseprotocolo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='episodiorehab',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVO')), fields=('cliente', 'protocolo'), name='un_episodio_activo_por_protocolo'),
        ),
        migrations.AlterUniqueTogether(
            name='registrodiariorehab',
            unique_together={('episodio', 'fecha')},
        ),
    ]
