# Generated by Django 5.2 on 2026-08-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodiariorehab',
            name='bandera_roja',
            field=models.BooleanField(default=False),
        ),
    ]
