# Generated by Django 5.2 on 2026-08-22 10:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import rehab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0002_registrodiariorehab_bandera_roja'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoRiesgoGymFaseRehab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('schema_version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('risk_tags', models.JSONField(validators=[rehab.models.validar_risk_tags])),
                ('pain_hold_min', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('freshness_days', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('action', models.CharField(choices=[('sostener', 'Sostener')], default='sostener', max_length=20)),
                ('scope', models.CharField(choices=[('matching_exercises', 'Ejercicios coincidentes')], default='matching_exercises', max_length=30)),
                ('red_flag_action', models.CharField(choices=[('proteger', 'Proteger')], default='proteger', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('vigente_desde', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_riesgo_gym', to='rehab.faseprotocolo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fase', 'version'), name='rehab_contrato_fase_version_unico')],
            },
        ),
    ]
