# Generated by Django 5.2 on 2026-02-15 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('clientes', '0003_fasecliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fase', models.CharField(help_text='Ej: Hipertrofia - Acumulación', max_length=100)),
                ('tipo_fase', models.CharField(choices=[('hipertrofia', 'Hipertrofia'), ('fuerza', 'Fuerza'), ('potencia', 'Potencia'), ('hipertrofia_especifica', 'Hipertrofia Específica'), ('hipertrofia_metabolica', 'Hipertrofia Metabólica'), ('descarga', 'Descarga')], max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('semanas_completadas', models.IntegerField(default=0)),
                ('semanas_planificadas', models.IntegerField(default=0)),
                ('rm_inicio', models.JSONField(default=dict, help_text="1RM al inicio de la fase: {'Sentadilla': 60.0, 'Press Banca': 80.0, ...}")),
                ('rm_fin', models.JSONField(blank=True, default=dict, help_text="1RM al final de la fase: {'Sentadilla': 65.0, 'Press Banca': 85.0, ...}", null=True)),
                ('ganancia_promedio', models.DecimalField(decimal_places=2, default=0, help_text='Ganancia promedio en % de todos los ejercicios', max_digits=5)),
                ('completada', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=False)),
                ('rpe_inicio', models.IntegerField(blank=True, null=True)),
                ('rpe_fin', models.IntegerField(blank=True, null=True)),
                ('rango_reps', models.CharField(blank=True, max_length=20, null=True)),
                ('volumen_multiplicador', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_fases', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Historial de Fase',
                'verbose_name_plural': 'Historial de Fases',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['cliente', 'activa'], name='analytics_h_cliente_b5d1a1_idx'), models.Index(fields=['cliente', 'completada'], name='analytics_h_cliente_05ee7f_idx')],
            },
        ),
    ]
