# Generated by Django 5.2 on 2026-01-17 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstiramientoEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('fase_recomendada', models.CharField(blank=True, choices=[('SUPERIOR', 'Tren superior'), ('INFERIOR', 'Tren inferior'), ('COMPLETO', 'Cuerpo completo')], max_length=12, null=True)),
                ('musculo_objetivo', models.CharField(blank=True, default='', max_length=120)),
                ('descripcion_corta', models.CharField(blank=True, default='', max_length=220)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='estiramientos/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstiramientoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('fase', models.CharField(choices=[('SUPERIOR', 'Tren superior'), ('INFERIOR', 'Tren inferior'), ('COMPLETO', 'Cuerpo completo')], max_length=12, unique=True)),
                ('transicion_segundos', models.PositiveIntegerField(default=5)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstiramientoPaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('duracion_segundos', models.PositiveIntegerField(default=30)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estiramientos.estiramientoejercicio')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='estiramientos.estiramientoplan')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('plan', 'orden')},
            },
        ),
    ]
