# Generated by Django 5.2 on 2026-09-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estiramientos', '0002_catalogo_movilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estiramientoejercicio',
            name='fase_recomendada',
            field=models.CharField(blank=True, choices=[('SUPERIOR', 'Tren superior'), ('INFERIOR', 'Tren inferior'), ('COMPLETO', 'Cuerpo completo'), ('CARDIO', 'Cardio / Recuperación activa')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='estiramientoplan',
            name='fase',
            field=models.CharField(choices=[('SUPERIOR', 'Tren superior'), ('INFERIOR', 'Tren inferior'), ('COMPLETO', 'Cuerpo completo'), ('CARDIO', 'Cardio / Recuperación activa')], max_length=12),
        ),
    ]
