# Generated by Django 5.2 on 2026-04-02 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_add_altura_cliente'),
        ('nutricion_app_django', '0003_nutricion_v2'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checknutricionaldiario',
            name='unique_check_cliente_fecha',
        ),
        migrations.RemoveConstraint(
            model_name='informeoptimizacion',
            name='unique_informe_cliente_semana',
        ),
        migrations.RemoveConstraint(
            model_name='targetnutricionaldiario',
            name='unique_target_cliente_fecha',
        ),
        migrations.AlterField(
            model_name='checknutricionaldiario',
            name='calidad_sueno',
            field=models.IntegerField(blank=True, help_text='Calidad del sueño (1=pésima, 10=perfecta)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='checknutricionaldiario',
            name='energia_entreno',
            field=models.IntegerField(blank=True, help_text='Energía durante el entreno (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='checknutricionaldiario',
            name='fatiga_percibida',
            field=models.IntegerField(blank=True, help_text='Fatiga percibida (1=ninguna, 10=agotamiento total)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='informeoptimizacion',
            name='ajuste_aplica_a',
            field=models.CharField(default='todos', help_text='gym | hyrox | descanso | todos — a qué tipo de día aplica', max_length=20),
        ),
        migrations.AlterField(
            model_name='informeoptimizacion',
            name='alerta_honestidad',
            field=models.BooleanField(default=False, help_text='True si los datos son contradictorios'),
        ),
        migrations.AlterField(
            model_name='informeoptimizacion',
            name='rendimiento_gym_delta_pct',
            field=models.FloatField(blank=True, help_text='% cambio en volumen total gym', null=True),
        ),
        migrations.AlterField(
            model_name='informeoptimizacion',
            name='rendimiento_hyrox_delta_pct',
            field=models.FloatField(blank=True, help_text='% cambio en tiempo/ritmo Hyrox', null=True),
        ),
        migrations.AlterField(
            model_name='perfilnutricional',
            name='safety_grasa_min_g_kg',
            field=models.FloatField(default=1.2, help_text='g grasa mínimos por kg de peso total'),
        ),
        migrations.AlterField(
            model_name='perfilnutricional',
            name='safety_proteina_min_g_kg',
            field=models.FloatField(default=1.8, help_text='g proteína mínimos por kg de masa magra'),
        ),
        migrations.AlterField(
            model_name='targetnutricionaldiario',
            name='bloques_verduras',
            field=models.IntegerField(default=3, help_text='Bloques fijos de verduras'),
        ),
        migrations.AlterUniqueTogether(
            name='checknutricionaldiario',
            unique_together={('cliente', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='informeoptimizacion',
            unique_together={('cliente', 'semana')},
        ),
        migrations.AlterUniqueTogether(
            name='targetnutricionaldiario',
            unique_together={('cliente', 'fecha')},
        ),
    ]
