# Generated by Django 5.2 on 2026-05-08 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeJOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('entreno_completado', 'Entreno completado'), ('apertura_manana', 'Apertura matutina'), ('ausencia_detectada', 'Ausencia sin lesión'), ('carga_anomala', 'Carga anómala ACWR'), ('pr_roto', 'Récord personal'), ('lesion_activa', 'Lesión activa'), ('fin_bloque', 'Fin de bloque')], max_length=30)),
                ('mensaje', models.TextField()),
                ('contexto', models.JSONField(default=dict)),
                ('leido', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_joi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
