# Generated by Django 5.2 on 2026-05-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0002_mensajejoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajejoi',
            name='trigger',
            field=models.CharField(choices=[('entreno_completado', 'Entreno completado'), ('apertura_manana', 'Apertura matutina'), ('ausencia_detectada', 'Ausencia sin lesión'), ('carga_anomala', 'Carga anómala ACWR'), ('pr_roto', 'Récord personal'), ('lesion_activa', 'Lesión activa'), ('fin_bloque', 'Fin de bloque'), ('hyrox_sesion_completada', 'Hyrox — sesión completada'), ('hyrox_readiness_bajo', 'Hyrox — readiness bajo'), ('hyrox_readiness_alto', 'Hyrox — readiness alto'), ('hyrox_cuenta_regresiva', 'Hyrox — cuenta regresiva'), ('hyrox_simulacion_completada', 'Hyrox — simulación completada'), ('hyrox_ausencia', 'Hyrox — ausencia detectada')], max_length=40),
        ),
    ]
