# Generated by Django 5.2 on 2026-05-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0004_alter_mensajejoi_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajejoi',
            name='feedback',
            field=models.CharField(blank=True, choices=[('clavado', 'Lo has clavado'), ('equivocado', 'Te has equivocado')], max_length=20, null=True),
        ),
    ]
