# Generated by Django 5.2 on 2026-05-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0005_mensajejoi_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajejoi',
            name='trigger',
            field=models.CharField(choices=[('entreno_completado', 'Entreno completado'), ('apertura_manana', 'Apertura matutina'), ('ausencia_detectada', 'Ausencia sin lesión'), ('carga_anomala', 'Carga anómala ACWR'), ('pr_roto', 'Récord personal'), ('lesion_activa', 'Lesión activa'), ('fin_bloque', 'Fin de bloque'), ('hyrox_sesion_completada', 'Hyrox — sesión completada'), ('hyrox_readiness_bajo', 'Hyrox — readiness bajo'), ('hyrox_readiness_alto', 'Hyrox — readiness alto'), ('hyrox_cuenta_regresiva', 'Hyrox — cuenta regresiva'), ('hyrox_simulacion_completada', 'Hyrox — simulación completada'), ('hyrox_ausencia', 'Hyrox — ausencia detectada'), ('decision_plan', 'Decisión del plan — intervención'), ('resumen_semanal', 'Resumen semanal — qué aprendió el plan'), ('hyrox_estancamiento_estacion', 'Hyrox — estancamiento por estación'), ('hyrox_deload_automatico', 'Hyrox — deload automático por TSB'), ('rpe_calibracion', 'Calibración RPE personal'), ('sintesis_joi', 'Síntesis autónoma — JOI en su propio tiempo')], max_length=40),
        ),
    ]
