# Generated by Django 5.2 on 2026-05-14 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0008_poda_manual_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manualdavid',
            name='confianza',
            field=models.FloatField(default=0.7, help_text='0.0–1.0. Decae con tiempo; se refuerza con evidencia.'),
        ),
        migrations.AddField(
            model_name='manualdavid',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('debilitada', 'Debilitada'), ('cuestionada', 'Cuestionada'), ('descartada', 'Descartada')], default='activa', max_length=15),
        ),
        migrations.AddField(
            model_name='manualdavid',
            name='hipotesis_contraria',
            field=models.TextField(blank=True, help_text='Interpretación alternativa que compite con esta hipótesis.', null=True),
        ),
        migrations.AddField(
            model_name='manualdavid',
            name='tipo',
            field=models.CharField(choices=[('dato_usuario', 'Dato del usuario'), ('preferencia', 'Preferencia'), ('patron', 'Patrón'), ('hipotesis', 'Hipótesis'), ('limite', 'Límite'), ('contradiccion', 'Contradicción')], default='hipotesis', max_length=20),
        ),
        migrations.AddField(
            model_name='manualdavid',
            name='ultima_evidencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NarrativaActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Interpretación longitudinal de JOI. No es verdad: es postura provisional.')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('cuestionada', 'Cuestionada'), ('congelada', 'Congelada'), ('descartada', 'Descartada')], default='borrador', max_length=15)),
                ('confianza', models.FloatField(default=0.5, help_text='0.0–1.0. Confianza de JOI en esta interpretación.')),
                ('version', models.PositiveIntegerField(default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='narrativa_joi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
