# Generated by Django 5.2 on 2026-05-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0009_manualdavid_confianza_manualdavid_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualdavid',
            name='notas_revision',
            field=models.TextField(blank=True, help_text='Razón del último cambio de confianza/estado, registrada por JOI.', null=True),
        ),
        migrations.AddField(
            model_name='narrativaactiva',
            name='ultima_revision_manual',
            field=models.DateTimeField(blank=True, help_text='Última vez que revisar_manual_david() ejecutó para este usuario.', null=True),
        ),
    ]
