# Generated by Django 5.2 on 2026-05-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0010_manualdavid_notas_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrativaactiva',
            name='capa_corta',
            field=models.TextField(blank=True, help_text='Estado reciente (días/semana).', null=True),
        ),
        migrations.AddField(
            model_name='narrativaactiva',
            name='capa_corta_actualizada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='narrativaactiva',
            name='capa_larga',
            field=models.TextField(blank=True, help_text='Identidad y patrones profundos.', null=True),
        ),
        migrations.AddField(
            model_name='narrativaactiva',
            name='capa_larga_actualizada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='narrativaactiva',
            name='capa_media',
            field=models.TextField(blank=True, help_text='Trayectoria de semanas.', null=True),
        ),
        migrations.AddField(
            model_name='narrativaactiva',
            name='capa_media_actualizada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='narrativaactiva',
            name='confianza',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='narrativaactiva',
            name='texto',
            field=models.TextField(blank=True, default='', help_text='Renderizado combinado de las tres capas. No editar directamente.'),
        ),
        migrations.AlterField(
            model_name='narrativaactiva',
            name='ultima_revision_manual',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
