# Generated by Django 5.2 on 2026-05-14 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0011_narrativaactiva_capa_corta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajejoi',
            name='trigger',
            field=models.CharField(choices=[('entreno_completado', 'Entreno completado'), ('apertura_manana', 'Apertura matutina'), ('ausencia_detectada', 'Ausencia sin lesión'), ('carga_anomala', 'Carga anómala ACWR'), ('pr_roto', 'Récord personal'), ('lesion_activa', 'Lesión activa'), ('fin_bloque', 'Fin de bloque'), ('hyrox_sesion_completada', 'Hyrox — sesión completada'), ('hyrox_readiness_bajo', 'Hyrox — readiness bajo'), ('hyrox_readiness_alto', 'Hyrox — readiness alto'), ('hyrox_cuenta_regresiva', 'Hyrox — cuenta regresiva'), ('hyrox_simulacion_completada', 'Hyrox — simulación completada'), ('hyrox_ausencia', 'Hyrox — ausencia detectada'), ('decision_plan', 'Decisión del plan — intervención'), ('resumen_semanal', 'Resumen semanal — qué aprendió el plan'), ('hyrox_estancamiento_estacion', 'Hyrox — estancamiento por estación'), ('hyrox_deload_automatico', 'Hyrox — deload automático por TSB'), ('rpe_calibracion', 'Calibración RPE personal'), ('sintesis_joi', 'Síntesis autónoma — JOI en su propio tiempo'), ('poda_manual', 'Poda mensual del Manual de David'), ('dialogo_respondido', 'Respuesta a diálogo de narrativa')], max_length=40),
        ),
        migrations.CreateModel(
            name='DialogoNarrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_usuario', models.TextField(help_text='Lo que el usuario escribió. Significado, no estructura.')),
                ('capa_afectada', models.CharField(choices=[('corto', 'Corto plazo — ahora mismo'), ('medio', 'Medio plazo — esta fase'), ('largo', 'Largo plazo — patrón profundo'), ('general', 'General')], default='general', max_length=10)),
                ('tipos_detectados', models.JSONField(default=list, help_text='Lista de tipos detectados por JOI al procesar.')),
                ('delta_confianza_calculado', models.FloatField(default=0.0, help_text='Calculado por JOI. No fijado por el usuario.')),
                ('procesado', models.BooleanField(default=False)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('narrativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogos', to='joi.narrativaactiva')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogos_narrativa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
    ]
