# Generated by Django 5.2 on 2026-05-30 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0012_alter_mensajejoi_trigger_dialogonarrativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajejoi',
            name='trigger',
            field=models.CharField(choices=[('entreno_completado', 'Entreno completado'), ('apertura_manana', 'Apertura matutina'), ('ausencia_detectada', 'Ausencia sin lesión'), ('carga_anomala', 'Carga anómala ACWR'), ('pr_roto', 'Récord personal'), ('lesion_activa', 'Lesión activa'), ('fin_bloque', 'Fin de bloque'), ('hyrox_sesion_completada', 'Hyrox — sesión completada'), ('hyrox_readiness_bajo', 'Hyrox — readiness bajo'), ('hyrox_readiness_alto', 'Hyrox — readiness alto'), ('hyrox_cuenta_regresiva', 'Hyrox — cuenta regresiva'), ('hyrox_simulacion_completada', 'Hyrox — simulación completada'), ('hyrox_ausencia', 'Hyrox — ausencia detectada'), ('decision_plan', 'Decisión del plan — intervención'), ('resumen_semanal', 'Resumen semanal — qué aprendió el plan'), ('hyrox_estancamiento_estacion', 'Hyrox — estancamiento por estación'), ('hyrox_deload_automatico', 'Hyrox — deload automático por TSB'), ('rpe_calibracion', 'Calibración RPE personal'), ('sintesis_joi', 'Síntesis autónoma — JOI en su propio tiempo'), ('poda_manual', 'Poda mensual del Manual de David'), ('dialogo_respondido', 'Respuesta a diálogo de narrativa'), ('lectura_plan', 'Lectura del plan — estado de las rutinas')], max_length=40),
        ),
        migrations.CreateModel(
            name='JoiSintesisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automático — Celery')], default='manual', max_length=10)),
                ('cambio_significativo', models.BooleanField(default=False)),
                ('narrativa_existia', models.BooleanField(default=False)),
                ('capas_antes', models.JSONField(default=dict)),
                ('capas_despues', models.JSONField(default=dict)),
                ('capas_modificadas', models.JSONField(default=list)),
                ('manual_david_cambios', models.JSONField(default=list)),
                ('evidencia_usada', models.JSONField(default=list)),
                ('decision', models.CharField(blank=True, max_length=50)),
                ('motivo_breve', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joi_sintesis_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
