# Generated by Django 5.2 on 2026-06-18 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0013_joisisntesislog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('motivo', models.CharField(max_length=50)),
                ('feedback', models.CharField(choices=[('encaja', 'Encaja'), ('no_encaja', 'No encaja')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joi_feedback_estados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback sobre encaje de estado',
                'verbose_name_plural': 'Feedbacks sobre encaje de estados',
                'ordering': ['-timestamp'],
                'unique_together': {('usuario', 'fecha', 'estado', 'motivo')},
            },
        ),
    ]
