# Generated by Django 5.2 on 2026-07-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0014_estadofeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajejoi',
            name='trigger',
            field=models.CharField(choices=[('entreno_completado', 'Entreno completado'), ('apertura_manana', 'Apertura matutina'), ('ausencia_detectada', 'Ausencia sin lesión'), ('carga_anomala', 'Carga anómala ACWR'), ('pr_roto', 'Récord personal'), ('lesion_activa', 'Lesión activa'), ('fin_bloque', 'Fin de bloque'), ('hyrox_sesion_completada', 'Hyrox — sesión completada'), ('hyrox_readiness_bajo', 'Hyrox — readiness bajo'), ('hyrox_readiness_alto', 'Hyrox — readiness alto'), ('hyrox_cuenta_regresiva', 'Hyrox — cuenta regresiva'), ('hyrox_simulacion_completada', 'Hyrox — simulación completada'), ('hyrox_ausencia', 'Hyrox — ausencia detectada'), ('decision_plan', 'Decisión del plan — intervención'), ('resumen_semanal', 'Resumen semanal — qué aprendió el plan'), ('hyrox_estancamiento_estacion', 'Hyrox — estancamiento por estación'), ('hyrox_deload_automatico', 'Hyrox — deload automático por TSB'), ('rpe_calibracion', 'Calibración RPE personal'), ('sintesis_joi', 'Síntesis autónoma — JOI en su propio tiempo'), ('poda_manual', 'Poda mensual del Manual de David'), ('dialogo_respondido', 'Respuesta a diálogo de narrativa'), ('lectura_plan', 'Lectura del plan — estado de las rutinas'), ('resultado_intervencion', 'Resultado de un ajuste temporal')], max_length=40),
        ),
    ]
