# Generated by Django 5.2 on 2026-08-22 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0015_alter_mensajejoi_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionManualDavidOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('confirmar', 'Confirmar'), ('cuestionar', 'Cuestionar'), ('descartar', 'Descartar'), ('posponer', 'Posponer'), ('deshacer', 'Deshacer')], max_length=12)),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('expected_fingerprint', models.CharField(max_length=64)),
                ('before_snapshot', models.JSONField(default=dict)),
                ('after_snapshot', models.JSONField(default=dict)),
                ('aplazada_hasta', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=240)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_revision_manual', to=settings.AUTH_USER_MODEL)),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_revision', to='joi.manualdavid')),
                ('reversa_de', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversion', to='joi.revisionmanualdavidoperacion')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['manual', '-created_at'], name='joi_rev_manual_fecha_idx'), models.Index(fields=['accion', 'aplazada_hasta'], name='joi_rev_accion_plazo_idx')],
            },
        ),
    ]
