# Generated by Django 5.2 on 2026-08-27 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0016_revisionmanualdavidoperacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoEntrenadorJOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('source_model', models.CharField(max_length=96)),
                ('source_id', models.PositiveBigIntegerField()),
                ('status', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('publicado', 'Publicado')], default='pendiente', max_length=16)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('ultimo_error', models.CharField(blank=True, max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('reclamado_en', models.DateTimeField(blank=True, null=True)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
                ('mensaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_entrenador', to='joi.mensajejoi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_entrenador_joi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creado_en', 'id'],
                'indexes': [models.Index(fields=['user', 'estado', 'creado_en'], name='joi_evt_user_estado_idx')],
                'constraints': [models.UniqueConstraint(fields=('event_type', 'source_model', 'source_id', 'status'), name='joi_evento_fuente_estado_unico')],
            },
        ),
    ]
