# Generated by Django 5.2 on 2026-02-01 11:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('volumen', 'Hipertrofia (Volumen)'), ('definicion', 'Definición (Corte)'), ('mantenimiento', 'Mantenimiento'), ('descarga', 'Descarga (Deload)')], max_length=20)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Fase del Cliente',
                'verbose_name_plural': 'Fases del Cliente',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
