# Generated by Django 5.2 on 2026-03-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_fasecliente'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bitacoradiaria',
            index=models.Index(fields=['cliente', 'fecha'], name='bitacora_cliente_fecha_idx'),
        ),
    ]
