# Generated by Django 5.2 on 2026-04-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_add_altura_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='api_token',
            field=models.CharField(blank=True, default='', help_text='Token de autenticación para el endpoint de Apple Health', max_length=64),
        ),
    ]
