# Generated by Django 5.2 on 2026-04-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_bitacoradiaria_fc_reposo_calidad_sueno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoradiaria',
            name='calidad_sueno',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Calidad del sueño (0-100)', null=True),
        ),
    ]
