# Generated by Django 5.2 on 2026-05-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_strava_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoradiaria',
            name='hrv_ms',
            field=models.PositiveSmallIntegerField(blank=True, help_text='HRV al despertar en ms (Garmin/Apple Watch/WHOOP)', null=True),
        ),
    ]
