# Generated by Django 5.2 on 2026-01-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0003_serierealizada_rpe_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='serierealizada',
            name='rpe_objetivo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
