# Generated by Django 5.2 on 2026-01-23 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('entrenos', '0004_serierealizada_rpe_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesafioSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del desafío', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción del desafío')),
                ('icono', models.CharField(default='🎯', help_text='Emoji del desafío', max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('objetivo_tipo', models.CharField(choices=[('sesiones', 'Número de Sesiones'), ('volumen', 'Volumen Total (kg)'), ('ejercicios', 'Ejercicios Diferentes'), ('duracion', 'Tiempo Total (minutos)'), ('racha', 'Días Consecutivos')], max_length=20)),
                ('objetivo_valor', models.PositiveIntegerField(help_text='Valor objetivo a alcanzar')),
                ('recompensa_puntos', models.PositiveIntegerField(default=50, help_text='Puntos que otorga completar el desafío')),
                ('activo', models.BooleanField(default=True)),
                ('global_challenge', models.BooleanField(default=True, help_text='Si es True, aplica a todos los clientes')),
            ],
            options={
                'verbose_name': 'Desafío Semanal',
                'verbose_name_plural': 'Desafíos Semanales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='LogroAutomatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del logro (ej: racha_7_dias)', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del logro (ej: Racha de Fuego 🔥)', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción de cómo desbloquear el logro')),
                ('icono', models.CharField(default='🏅', help_text='Emoji o icono del logro', max_length=10)),
                ('categoria', models.CharField(choices=[('racha', '🔥 Racha'), ('volumen', '💪 Volumen'), ('tiempo', '⏱️ Tiempo'), ('records', '🏆 Récords'), ('perfeccion', '⭐ Perfección'), ('especial', '🎯 Especial')], default='especial', max_length=20)),
                ('rareza', models.CharField(choices=[('comun', 'Común'), ('raro', 'Raro'), ('epico', 'Épico'), ('legendario', 'Legendario')], default='comun', max_length=20)),
                ('condicion_tipo', models.CharField(help_text='Tipo de condición (racha_dias, volumen_sesion, etc)', max_length=50)),
                ('condicion_valor', models.JSONField(default=dict, help_text='Parámetros de la condición en JSON')),
                ('puntos_recompensa', models.PositiveIntegerField(default=10, help_text='Puntos que otorga este logro')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Logro Automático',
                'verbose_name_plural': 'Logros Automáticos',
                'ordering': ['rareza', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='serierealizada',
            name='rpe_objetivo',
        ),
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_minutos', models.PositiveIntegerField(help_text='Duración total de la sesión en minutos')),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('series_completadas', models.PositiveIntegerField(default=0)),
                ('series_totales', models.PositiveIntegerField(default=0)),
                ('ejercicios_completados', models.PositiveIntegerField(default=0)),
                ('ejercicios_totales', models.PositiveIntegerField(default=0)),
                ('rpe_medio', models.FloatField(blank=True, help_text='RPE promedio de la sesión (1-10)', null=True)),
                ('volumen_sesion', models.DecimalField(decimal_places=2, default=0, help_text='Volumen total en kg', max_digits=10)),
                ('nuevos_records', models.PositiveIntegerField(default=0, help_text='Número de récords personales establecidos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('entreno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sesion_detalle', to='entrenos.entrenorealizado')),
                ('logros_desbloqueados', models.ManyToManyField(blank=True, related_name='sesiones', to='entrenos.logroautomatico')),
            ],
            options={
                'verbose_name': 'Sesión de Entrenamiento',
                'verbose_name_plural': 'Sesiones de Entrenamiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso_actual', models.PositiveIntegerField(default=0, help_text='Progreso actual hacia el objetivo')),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_desafios', to='clientes.cliente')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='entrenos.desafiosemanal')),
            ],
            options={
                'verbose_name': 'Progreso de Desafío',
                'verbose_name_plural': 'Progresos de Desafíos',
                'ordering': ['-ultima_actualizacion'],
                'unique_together': {('cliente', 'desafio')},
            },
        ),
        migrations.CreateModel(
            name='RecordPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio_nombre', models.CharField(help_text='Nombre del ejercicio', max_length=200)),
                ('tipo_record', models.CharField(choices=[('peso_maximo', 'Peso Máximo'), ('volumen_total', 'Volumen Total'), ('reps_maximas', 'Repeticiones Máximas'), ('one_rep_max', '1RM Estimado')], default='peso_maximo', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor del récord (kg, reps, etc)', max_digits=10)),
                ('fecha_logrado', models.DateField(auto_now_add=True)),
                ('superado', models.BooleanField(default=False, help_text='True si este récord fue superado posteriormente')),
                ('fecha_superado', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_personales', to='clientes.cliente')),
                ('entreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_establecidos', to='entrenos.entrenorealizado')),
            ],
            options={
                'verbose_name': 'Récord Personal',
                'verbose_name_plural': 'Récords Personales',
                'ordering': ['-fecha_logrado'],
                'indexes': [models.Index(fields=['cliente', 'ejercicio_nombre', 'tipo_record'], name='entrenos_re_cliente_e623a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClienteLogroAutomatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueo', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros_automaticos', to='clientes.cliente')),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_desbloqueados', to='entrenos.logroautomatico')),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logros_obtenidos', to='entrenos.sesionentrenamiento')),
            ],
            options={
                'verbose_name': 'Logro Desbloqueado',
                'verbose_name_plural': 'Logros Desbloqueados',
                'ordering': ['-fecha_desbloqueo'],
                'unique_together': {('cliente', 'logro')},
            },
        ),
    ]
