# Generated by Django 5.2 on 2026-01-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0005_desafiosemanal_logroautomatico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionentrenamiento',
            name='acwr',
            field=models.FloatField(blank=True, help_text='Ratio ACWR de la sesión', null=True),
        ),
    ]
