# Generated by Django 5.2 on 2026-03-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0006_sesionentrenamiento_acwr'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejerciciorealizado',
            name='is_recovery_load',
            field=models.BooleanField(default=False, help_text='True si este ejercicio se realizó bajo un estado biológico restringido (volume_modifier < 1.0)'),
        ),
    ]
