# Generated by Django 5.2 on 2026-03-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_add_performance_indexes'),
        ('entrenos', '0007_ejerciciorealizado_is_recovery_load'),
        ('rutinas', '0003_ejerciciobase_tipo_progresion'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entrenorealizado',
            index=models.Index(fields=['cliente', 'fecha'], name='entreno_cliente_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='serierealizada',
            index=models.Index(fields=['entreno'], name='serie_entreno_idx'),
        ),
    ]
