# Generated by Django 5.2 on 2026-04-02 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_add_altura_cliente'),
        ('entrenos', '0009_ejerciciorealizado_molestia'),
        ('hyrox', '0013_alter_hyroxactivity_tipo_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gym', 'Gimnasio / Fuerza'), ('hyrox', 'Sesión Hyrox'), ('carrera', 'Carrera / Running'), ('ciclismo', 'Ciclismo'), ('remo', 'Remo / Ergómetro'), ('futbol', 'Fútbol'), ('natacion', 'Natación'), ('yoga', 'Yoga / Movilidad'), ('estiramientos', 'Estiramientos'), ('otro', 'Otra Actividad')], default='gym', max_length=20)),
                ('titulo', models.CharField(blank=True, help_text="Nombre libre de la sesión (ej: 'Pierna A', 'Hyrox Semana 3')", max_length=200)),
                ('fecha', models.DateField(db_index=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('duracion_minutos', models.PositiveIntegerField(blank=True, help_text='Duración total de la sesión en minutos', null=True)),
                ('volumen_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Volumen total en kg (peso × series × reps). Null para cardio puro.', max_digits=10, null=True)),
                ('distancia_metros', models.PositiveIntegerField(blank=True, help_text='Distancia recorrida en metros (para cardio/running)', null=True)),
                ('carga_ua', models.FloatField(blank=True, help_text='Carga en Unidades Arbitrarias = RPE × duración_minutos (para ACWR)', null=True)),
                ('rpe_medio', models.FloatField(blank=True, help_text='RPE medio de la sesión (escala 1-10)', null=True)),
                ('calorias', models.PositiveIntegerField(blank=True, null=True)),
                ('fuente', models.CharField(choices=[('manual', 'Registro manual'), ('liftin', 'Importado de Liftin'), ('hyrox_engine', 'Motor Hyrox'), ('auto', 'Generado automáticamente')], default='manual', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_realizadas', to='clientes.cliente')),
                ('entreno_gym', models.OneToOneField(blank=True, help_text='Enlace al EntrenoRealizado para sesiones de gimnasio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_actividad', to='entrenos.entrenorealizado')),
                ('sesion_hyrox', models.OneToOneField(blank=True, help_text='Enlace a HyroxSession para sesiones del motor hyrox', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_actividad', to='hyrox.hyroxsession')),
            ],
            options={
                'verbose_name': 'Actividad Realizada',
                'verbose_name_plural': 'Actividades Realizadas',
                'ordering': ['-fecha', '-hora_inicio'],
                'indexes': [models.Index(fields=['cliente', 'fecha'], name='actividad_cliente_fecha_idx'), models.Index(fields=['cliente', 'tipo'], name='actividad_cliente_tipo_idx')],
            },
        ),
    ]
