# Generated by Django 5.2 on 2026-04-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0010_hub_actividad_realizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadrealizada',
            name='fecha_realizado',
            field=models.DateField(blank=True, db_index=True, help_text="Fecha real de ejecución. Si es null, se asume igual a 'fecha'.", null=True),
        ),
    ]
