# Generated by Django 5.2 on 2026-04-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0011_add_fecha_realizado_actividad_realizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejerciciorealizado',
            name='es_tope_maquina',
            field=models.BooleanField(default=False, help_text='True si el peso recomendado supera el máximo físico de la máquina. Congela progresión de peso y avanza por reps/tempo.'),
        ),
    ]
