# Generated by Django 5.2 on 2026-04-28 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_strava_models'),
        ('entrenos', '0012_ejerciciorealizado_es_tope_maquina'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymAdaptationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.CharField(max_length=120)),
                ('incremento_peso_pct', models.FloatField(default=5.0, help_text='% de incremento preferido')),
                ('reduccion_peso_pct', models.FloatField(default=10.0, help_text='% de reducción preferida')),
                ('decisiones_totales', models.IntegerField(default=0)),
                ('decisiones_validadas', models.IntegerField(default=0)),
                ('decisiones_fallidas', models.IntegerField(default=0)),
                ('confianza', models.CharField(default='baja', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_adaptation_profiles', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Perfil de Adaptación',
                'verbose_name_plural': 'Perfiles de Adaptación',
                'unique_together': {('cliente', 'ejercicio')},
            },
        ),
        migrations.CreateModel(
            name='GymDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.CharField(max_length=120)),
                ('peso_anterior', models.FloatField(blank=True, null=True)),
                ('reps_anteriores', models.PositiveIntegerField(blank=True, null=True)),
                ('rpe_anterior', models.FloatField(blank=True, null=True)),
                ('accion', models.CharField(choices=[('subir_peso', 'Subir peso'), ('subir_reps', 'Subir repeticiones'), ('mantener', 'Mantener'), ('bajar_peso', 'Reducir peso'), ('deload', 'Descarga'), ('cambiar_variante', 'Cambiar variante')], max_length=30)),
                ('valor_cambio', models.FloatField(blank=True, null=True)),
                ('motivo', models.TextField()),
                ('resultado', models.CharField(blank=True, choices=[('validada', 'Validada'), ('fallida', 'Fallida'), ('neutra', 'Neutra')], max_length=20, null=True)),
                ('notas_resultado', models.TextField(blank=True, null=True)),
                ('confianza', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_decision_logs', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Decisión de Progresión',
                'verbose_name_plural': 'Decisiones de Progresión',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['cliente', 'ejercicio'], name='decision_cliente_ejercicio_idx')],
            },
        ),
    ]
