# Generated by Django 5.2 on 2026-05-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0013_gym_decision_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenorealizado',
            name='energia_pre_sesion',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Energía percibida antes de la sesión (1-10)', null=True),
        ),
    ]
