# Generated by Django 5.2 on 2026-05-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0014_add_energia_pre_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='serierealizada',
            name='tecnica_calidad',
            field=models.CharField(blank=True, choices=[('buena', 'Buena'), ('aceptable', 'Aceptable'), ('comprometida', 'Comprometida')], help_text='Calidad de técnica percibida en esta serie', max_length=15, null=True),
        ),
    ]
