# Generated by Django 5.2 on 2026-05-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0015_add_tecnica_calidad_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadrealizada',
            name='hr_maxima',
            field=models.PositiveIntegerField(blank=True, help_text='FC máxima de la sesión en lpm (fuente: Strava / dispositivo)', null=True),
        ),
        migrations.AddField(
            model_name='actividadrealizada',
            name='hr_media',
            field=models.PositiveIntegerField(blank=True, help_text='FC media de la sesión en lpm (fuente: Strava / dispositivo)', null=True),
        ),
        migrations.AlterField(
            model_name='actividadrealizada',
            name='fuente',
            field=models.CharField(choices=[('manual', 'Registro manual'), ('liftin', 'Importado de Liftin'), ('hyrox_engine', 'Motor Hyrox'), ('strava', 'Importado de Strava'), ('auto', 'Generado automáticamente')], default='manual', max_length=20),
        ),
    ]
