# Generated by Django 5.2 on 2026-05-17 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_add_hrv_ms_to_bitacora'),
        ('entrenos', '0016_actividad_hr_media_hr_maxima_strava'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prevista', models.DateField(db_index=True)),
                ('fecha_realizada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('saltada_usuario', 'Saltada por usuario'), ('omitida_sistema', 'Omitida por sistema'), ('cancelada_lesion', 'Cancelada por lesión')], db_index=True, default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('normal', 'Normal')], default='alta', max_length=10)),
                ('nombre_sesion', models.CharField(blank=True, max_length=200)),
                ('bloque_nombre', models.CharField(blank=True, max_length=100)),
                ('dia_numero', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('motivo_estado', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_programadas', to='clientes.cliente')),
                ('entreno_realizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_programadas', to='entrenos.entrenorealizado')),
            ],
            options={
                'ordering': ['fecha_prevista', 'id'],
                'indexes': [models.Index(fields=['cliente', 'estado', 'fecha_prevista'], name='entrenos_se_cliente_e47ea4_idx')],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'fecha_prevista'), name='unique_sesion_cliente_fecha')],
            },
        ),
    ]
