# Generated by Django 5.2 on 2026-05-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0017_sesion_programada'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionprogramada',
            name='pospuesta_hasta',
            field=models.DateField(blank=True, db_index=True, help_text='Si está presente, la sesión no se muestra como pendiente hasta esa fecha.', null=True),
        ),
    ]
