# Generated by Django 5.2 on 2026-05-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0018_pospuesta_hasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenorealizado',
            name='modo_reducido',
            field=models.BooleanField(default=False, help_text='True si la sesión se realizó en modo esencial (solo bloque principal).'),
        ),
    ]
