# Generated by Django 5.2 on 2026-05-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0019_modo_reducido'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejerciciorealizado',
            name='es_bloque_principal',
            field=models.BooleanField(blank=True, help_text='True=bloque principal, False=opcional, None=sesión normal (no esencial).', null=True),
        ),
    ]
