# Generated by Django 5.2 on 2026-05-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0020_es_bloque_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenorealizado',
            name='opcionales_planificados',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nº de ejercicios opcionales planificados en modo esencial.', null=True),
        ),
        migrations.AddField(
            model_name='entrenorealizado',
            name='principales_planificados',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nº de ejercicios principales planificados en modo esencial.', null=True),
        ),
    ]
