# Generated by Django 5.2 on 2026-05-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_add_hrv_ms_to_bitacora'),
        ('entrenos', '0021_denominadores_esencial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patron', models.CharField(db_index=True, max_length=60)),
                ('texto', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('ignorada', 'Ignorada por ahora'), ('aplicada', 'Aplicada'), ('descartada', 'Descartada')], db_index=True, default='pendiente', max_length=20)),
                ('cooldown_hasta', models.DateField(blank=True, db_index=True, null=True)),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias_plan', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-fecha_generada'],
                'indexes': [models.Index(fields=['cliente', 'patron', 'estado'], name='entrenos_su_cliente_2b107b_idx')],
            },
        ),
    ]
