# Generated by Django 5.2 on 2026-05-17 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_add_hrv_ms_to_bitacora'),
        ('entrenos', '0022_sugerencia_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervencionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('no_subir_cargas', 'No subir cargas'), ('reducir_accesorios', 'Reducir accesorios'), ('mantener_estructura', 'Mantener estructura')], db_index=True, max_length=30)),
                ('origen_patron', models.CharField(blank=True, max_length=60)),
                ('fecha_inicio', models.DateField(db_index=True)),
                ('fecha_fin', models.DateField(db_index=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada')], db_index=True, default='activa', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones_plan', to='clientes.cliente')),
                ('sugerencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervenciones', to='entrenos.sugerenciaplan')),
            ],
            options={
                'ordering': ['-creada_en'],
                'indexes': [models.Index(fields=['cliente', 'estado', 'fecha_fin'], name='entrenos_in_cliente_8990a3_idx')],
            },
        ),
    ]
