# Generated by Django 5.2 on 2026-05-17 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_add_hrv_ms_to_bitacora'),
        ('entrenos', '0023_intervencion_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervencionplan',
            name='tipo',
            field=models.CharField(choices=[('no_subir_cargas', 'No subir cargas'), ('reducir_accesorios', 'Reducir accesorios'), ('mantener_estructura', 'Mantener estructura'), ('redistrib_dia_frecuente', 'Redistribuir día con muchas caídas'), ('redistrib_dias_menores', 'Probar semana con menos días'), ('redistrib_pierna_futbol', 'Separar pierna de fútbol'), ('redistrib_aligerar_dia', 'Aligerar día con versiones esenciales')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='PreferenciaPlanAprendida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('evitar_pierna_tras_futbol', 'Evitar pierna cerca del fútbol'), ('evitar_dia_frecuente', 'Evitar sesión principal en día problemático'), ('preferir_menos_dias', 'Preferir estructura real de menos días'), ('aligerar_dia_concreto', 'Aligerar accesorios en un día concreto')], db_index=True, max_length=40)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('suspendida', 'Suspendida'), ('revocada', 'Revocada')], db_index=True, default='activa', max_length=20)),
                ('evidencia_count', models.PositiveSmallIntegerField(default=2, help_text='Number of favorable probes that originated this preference.')),
                ('origen_patron', models.CharField(blank=True, help_text="e.g. 'redistrib_pierna_futbol'", max_length=60)),
                ('descripcion', models.TextField(blank=True, help_text='Human-readable description shown to the user.')),
                ('fecha_inicio', models.DateField()),
                ('ultima_confirmacion', models.DateField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Extra info: e.g. {dia: 'lunes', umbral_horas: 48}")),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_plan', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
                'unique_together': {('cliente', 'tipo', 'estado')},
            },
        ),
    ]
