# Generated by Django 5.2 on 2026-05-18 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_add_hrv_ms_to_bitacora'),
        ('entrenos', '0024_preferencia_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymDecisionTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('decision_estado', models.CharField(max_length=50)),
                ('causa_principal', models.CharField(blank=True, max_length=80)),
                ('senales_motor', models.JSONField(default=dict)),
                ('capas_visibles', models.JSONField(default=list)),
                ('capas_suprimidas', models.JSONField(default=list)),
                ('explicacion_senales', models.JSONField(default=list)),
                ('preferencias_activas', models.JSONField(default=list)),
                ('intervenciones_activas', models.JSONField(default=list)),
                ('lesion_contexto', models.JSONField(default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_traces', to='clientes.cliente')),
                ('sesion_programada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entrenos.sesionprogramada')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
                'indexes': [models.Index(fields=['cliente', 'fecha'], name='entrenos_gy_cliente_e05f1e_idx')],
                'unique_together': {('cliente', 'fecha')},
            },
        ),
    ]
