# Generated by Django 5.2 on 2026-05-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0026_gym_decision_trace_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervencionplan',
            name='tipo',
            field=models.CharField(choices=[('no_subir_cargas', 'No subir cargas'), ('reducir_accesorios', 'Reducir accesorios'), ('mantener_estructura', 'Mantener estructura'), ('redistrib_dia_frecuente', 'Redistribuir día con muchas caídas'), ('redistrib_dias_menores', 'Probar semana con menos días'), ('redistrib_pierna_futbol', 'Separar pierna de fútbol'), ('redistrib_aligerar_dia', 'Aligerar día con versiones esenciales'), ('vigilar_senal', 'Observar señal durante 2 semanas')], db_index=True, max_length=30),
        ),
    ]
