# Generated by Django 5.2 on 2026-06-06 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_add_hrv_ms_to_bitacora'),
        ('entrenos', '0027_vigilar_senal_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PausaEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Primer día de la pausa (último gym + 1).')),
                ('fecha_fin', models.DateField(blank=True, help_text='Día en que se retomó. Null = pausa abierta.', null=True)),
                ('dias_sin_gym', models.PositiveIntegerField(default=0)),
                ('nivel', models.CharField(choices=[('clara', 'Pausa clara'), ('larga', 'Pausa larga'), ('recalibracion', 'Recalibración')], max_length=20)),
                ('motivo', models.CharField(choices=[('desconocido', 'Desconocido'), ('enfermedad', 'Enfermedad'), ('molestia_lesion', 'Molestia / lesión'), ('vacaciones_viaje', 'Vacaciones / viaje'), ('trabajo_no_pude', 'Trabajo / no pude'), ('descanso_decidido', 'Descanso decidido'), ('otro', 'Otro'), ('prefiero_no_decirlo', 'Prefiero no decirlo')], default='desconocido', max_length=40)),
                ('motivo_preguntado', models.BooleanField(default=False)),
                ('motivo_respondido', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pausas_entrenamiento', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['cliente', 'fecha_fin'], name='entrenos_pa_cliente_f2ee15_idx')],
            },
        ),
    ]
