# Generated by Django 5.2 on 2026-06-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0028_pausaentrenamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymdecisionlog',
            name='estado_aplicacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aplicada', 'Aplicada'), ('pospuesta', 'Pospuesta')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='gymdecisionlog',
            name='fecha_aplicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymdecisionlog',
            name='motivo_postergacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
