# Generated by Django 5.2 on 2026-08-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0030_sugerenciaplan_contrato_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenorealizado',
            name='fecha_ejecucion',
            field=models.DateField(blank=True, db_index=True, help_text="Día real en que se guardó la sesión (timezone.localdate() en el momento del guardado), distinto de 'fecha' que es el día del plan al que pertenece la rutina.", null=True),
        ),
    ]
