# Generated by Django 5.2 on 2026-08-10 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_add_hrv_ms_to_bitacora'),
        ('entrenos', '0033_gymdecisionversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionprogramada',
            name='semana_prescrita',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='ContratoSemanalGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.DateField(db_index=True)),
                ('objetivo_sesiones', models.PositiveSmallIntegerField()),
                ('minimo_valido', models.PositiveSmallIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_semanales_gym', to='clientes.cliente')),
            ],
            options={
                'ordering': ['semana', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sesionprogramada',
            name='contrato_semanal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='entrenos.contratosemanalgym'),
        ),
        migrations.CreateModel(
            name='EstrategiaSemanalGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('objetivo_sesiones', models.PositiveSmallIntegerField()),
                ('minimo_valido', models.PositiveSmallIntegerField()),
                ('vigente_desde', models.DateField(db_index=True)),
                ('vigente_hasta', models.DateField(blank=True, db_index=True, null=True)),
                ('estado', models.CharField(choices=[('aprobada', 'Aprobada'), ('retirada', 'Retirada')], default='aprobada', max_length=12)),
                ('motivo', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estrategias_gym_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estrategias_semanales_gym', to='clientes.cliente')),
            ],
            options={
                'ordering': ['cliente_id', 'version'],
            },
        ),
        migrations.AddField(
            model_name='contratosemanalgym',
            name='estrategia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='entrenos.estrategiasemanalgym'),
        ),
        migrations.AddConstraint(
            model_name='estrategiasemanalgym',
            constraint=models.UniqueConstraint(fields=('cliente', 'version'), name='uniq_estrategia_gym_cliente_version'),
        ),
        migrations.AddConstraint(
            model_name='estrategiasemanalgym',
            constraint=models.CheckConstraint(condition=models.Q(('minimo_valido__lte', models.F('objetivo_sesiones'))), name='estrategia_gym_minimo_lte_objetivo'),
        ),
        migrations.AddConstraint(
            model_name='estrategiasemanalgym',
            constraint=models.CheckConstraint(condition=models.Q(('minimo_valido__gte', 1)), name='estrategia_gym_minimo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='estrategiasemanalgym',
            constraint=models.CheckConstraint(condition=models.Q(('objetivo_sesiones__lte', 7)), name='estrategia_gym_objetivo_maximo_siete'),
        ),
        migrations.AddConstraint(
            model_name='contratosemanalgym',
            constraint=models.UniqueConstraint(fields=('cliente', 'semana'), name='uniq_contrato_gym_cliente_semana'),
        ),
        migrations.AddConstraint(
            model_name='contratosemanalgym',
            constraint=models.CheckConstraint(condition=models.Q(('minimo_valido__lte', models.F('objetivo_sesiones'))), name='contrato_gym_minimo_lte_objetivo'),
        ),
    ]
