# Generated by Django 5.2 on 2026-08-15 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_add_hrv_ms_to_bitacora'),
        ('entrenos', '0034_sesionprogramada_semana_prescrita_contratosemanalgym_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentoVarianteGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.JSONField()),
                ('original_normalizado', models.CharField(db_index=True, max_length=160)),
                ('variante', models.JSONField()),
                ('variante_normalizada', models.CharField(db_index=True, max_length=160)),
                ('baseline', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('favorable', 'Favorable'), ('fallida', 'Fallida'), ('insuficiente', 'Insuficiente')], db_index=True, default='activa', max_length=16)),
                ('iniciada_en', models.DateTimeField()),
                ('vence_en', models.DateTimeField(db_index=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_cierre', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimentos_variante_gym', to='clientes.cliente')),
                ('decision_origen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experimento_variante', to='entrenos.gymdecisionlog')),
            ],
            options={
                'ordering': ['-iniciada_en', '-id'],
            },
        ),
        migrations.AddField(
            model_name='ejerciciorealizado',
            name='experimento_variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejecuciones', to='entrenos.experimentovariantegym'),
        ),
        migrations.AddIndex(
            model_name='experimentovariantegym',
            index=models.Index(fields=['cliente', 'estado'], name='expvar_cliente_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='experimentovariantegym',
            index=models.Index(fields=['cliente', 'original_normalizado'], name='expvar_cliente_orig_idx'),
        ),
    ]
