# Generated by Django 5.2 on 2026-08-15 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_add_hrv_ms_to_bitacora'),
        ('entrenos', '0035_experimentovariantegym_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervencionMolestiaGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_canonica', models.CharField(db_index=True, max_length=40)),
                ('risk_tags_snapshot', models.JSONField(default=list)),
                ('original', models.JSONField()),
                ('original_normalizado', models.CharField(db_index=True, max_length=160)),
                ('alternativa', models.JSONField(default=dict)),
                ('alternativa_normalizada', models.CharField(blank=True, db_index=True, max_length=160)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('favorable', 'Favorable'), ('fallida', 'Fallida'), ('insuficiente', 'Insuficiente')], db_index=True, default='activa', max_length=16)),
                ('iniciada_en', models.DateTimeField()),
                ('vence_en', models.DateTimeField(db_index=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_cierre', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones_molestia_gym', to='clientes.cliente')),
                ('decision_origen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervencion_molestia', to='entrenos.gymdecisionlog')),
            ],
            options={
                'ordering': ['-iniciada_en', '-id'],
            },
        ),
        migrations.AddField(
            model_name='ejerciciorealizado',
            name='intervencion_molestia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejecuciones', to='entrenos.intervencionmolestiagym'),
        ),
        migrations.AddIndex(
            model_name='intervencionmolestiagym',
            index=models.Index(fields=['cliente', 'estado'], name='intmol_cliente_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='intervencionmolestiagym',
            index=models.Index(fields=['cliente', 'zona_canonica', 'original_normalizado'], name='intmol_cliente_zona_orig_idx'),
        ),
    ]
