# Generated by Django 5.2 on 2026-08-15 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_add_hrv_ms_to_bitacora'),
        ('entrenos', '0036_intervencionmolestiagym_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloDeload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado')], db_index=True, default='activo', max_length=16)),
                ('alcance', models.CharField(default='global', max_length=16)),
                ('causa', models.CharField(choices=[('fatiga_gym', 'Fatiga detectada en Gym'), ('tsb_hyrox', 'TSB de seguridad Hyrox'), ('manual', 'Decisión manual')], max_length=32)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_prevista', models.DateField()),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('metrica', models.CharField(blank=True, max_length=40)),
                ('umbral', models.FloatField(blank=True, null=True)),
                ('valor_apertura', models.FloatField(blank=True, null=True)),
                ('evidencia', models.JSONField(blank=True, default=dict)),
                ('politica_snapshot', models.JSONField(default=dict)),
                ('resultado', models.CharField(blank=True, choices=[('favorable', 'Favorable'), ('fallido', 'Fallido'), ('insuficiente', 'Datos insuficientes')], max_length=20, null=True)),
                ('motivo_cierre', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_deload', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-fecha_inicio', '-pk'],
                'indexes': [models.Index(fields=['cliente', 'estado'], name='deload_cliente_estado_idx')],
            },
        ),
    ]
