# Generated by Django 5.2.4 on 2026-08-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0045_entrenorealizado_sello_causal_gym'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionSupervisionGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('ejecutada_conforme', 'Ejecutada conforme'), ('proteccion_cumplida', 'Protección cumplida'), ('desviada', 'Desviada'), ('inconclusa', 'Inconclusa')], max_length=24)),
                ('evidencia_snapshot', models.JSONField(default=dict)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('calculo_version', models.PositiveSmallIntegerField(default=1)),
                ('evaluada_en', models.DateTimeField(auto_now_add=True)),
                ('version_decision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evaluacion_supervision', to='entrenos.gymdecisionversion')),
            ],
            options={
                'ordering': ['-evaluada_en', '-pk'],
            },
        ),
    ]
