# Generated by Django 5.2 on 2026-08-22 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_add_hrv_ms_to_bitacora'),
        ('entrenos', '0046_evaluacionsupervisiongym'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contratosemanalgym',
            name='indice_semana_bloque',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ContratoBloqueGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('propuesto', 'Propuesto'), ('activo', 'Activo'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado'), ('retirado', 'Retirado')], db_index=True, default='propuesto', max_length=12)),
                ('semana_inicio', models.DateField(db_index=True)),
                ('semanas_previstas', models.PositiveSmallIntegerField()),
                ('semana_fin_prevista', models.DateField(db_index=True)),
                ('objetivo_sesiones', models.PositiveSmallIntegerField()),
                ('minimo_valido', models.PositiveSmallIntegerField()),
                ('objetivo_principal', models.CharField(max_length=80)),
                ('objetivos_secundarios', models.JSONField(default=list)),
                ('limites_snapshot', models.JSONField(default=dict)),
                ('motor_nombre', models.CharField(max_length=80)),
                ('motor_version', models.CharField(max_length=40)),
                ('fingerprint', models.CharField(max_length=64)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques_gym_aprobados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_bloque_gym', to='clientes.cliente')),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloques', to='entrenos.estrategiasemanalgym')),
                ('predecesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sucesores', to='entrenos.contratobloquegym')),
            ],
            options={
                'ordering': ['cliente_id', 'version'],
            },
        ),
        migrations.AddField(
            model_name='contratosemanalgym',
            name='bloque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_semanales', to='entrenos.contratobloquegym'),
        ),
        migrations.AddConstraint(
            model_name='contratosemanalgym',
            constraint=models.UniqueConstraint(fields=('bloque', 'indice_semana_bloque'), name='uniq_contrato_gym_bloque_indice'),
        ),
        migrations.AddConstraint(
            model_name='contratobloquegym',
            constraint=models.UniqueConstraint(fields=('cliente', 'version'), name='uniq_bloque_gym_cliente_version'),
        ),
        migrations.AddConstraint(
            model_name='contratobloquegym',
            constraint=models.UniqueConstraint(fields=('cliente', 'fingerprint'), name='uniq_bloque_gym_cliente_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='contratobloquegym',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['activo', 'pausado'])), fields=('cliente',), name='uniq_bloque_gym_abierto_cliente'),
        ),
        migrations.AddConstraint(
            model_name='contratobloquegym',
            constraint=models.CheckConstraint(condition=models.Q(('semanas_previstas__gte', 1)), name='bloque_gym_semanas_positivas'),
        ),
        migrations.AddConstraint(
            model_name='contratobloquegym',
            constraint=models.CheckConstraint(condition=models.Q(('minimo_valido__lte', models.F('objetivo_sesiones'))), name='bloque_gym_minimo_lte_objetivo'),
        ),
    ]
