# Generated by Django 5.2 on 2026-08-22 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0047_contratosemanalgym_indice_semana_bloque_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionBloqueGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_calculo', models.PositiveIntegerField()),
                ('fingerprint_evidencia', models.CharField(max_length=64)),
                ('estado_resultado', models.CharField(choices=[('objetivo_sostenido', 'Objetivo sostenido'), ('minimo_sostenido', 'Mínimo sostenido'), ('deriva_observada', 'Deriva observada'), ('interrumpido_seguridad', 'Interrumpido por seguridad'), ('evidencia_insuficiente', 'Evidencia insuficiente')], max_length=28)),
                ('evidencia_snapshot', models.JSONField(default=dict)),
                ('estado_revision', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], db_index=True, default='pendiente', max_length=10)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='entrenos.contratobloquegym')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_bloque_gym_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['bloque_id', 'version_calculo'],
                'constraints': [models.UniqueConstraint(fields=('bloque', 'version_calculo'), name='uniq_eval_bloque_gym_version'), models.UniqueConstraint(fields=('bloque', 'fingerprint_evidencia'), name='uniq_eval_bloque_gym_fingerprint')],
            },
        ),
    ]
