# Generated by Django 5.2 on 2026-09-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0049_senalentrenamientoautorizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejerciciorealizado',
            name='multiplicador_carga',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ejerciciorealizado',
            name='peso_total_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ejerciciorealizado',
            name='tipo_carga',
            field=models.CharField(blank=True, choices=[('total', 'Peso total'), ('por_mano', 'Por mano'), ('por_lado', 'Por lado')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='serierealizada',
            name='multiplicador_carga',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serierealizada',
            name='peso_total_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='serierealizada',
            name='tipo_carga',
            field=models.CharField(blank=True, choices=[('total', 'Peso total'), ('por_mano', 'Por mano'), ('por_lado', 'Por lado')], max_length=10, null=True),
        ),
    ]
