# Generated by Django 5.2 on 2026-09-09 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_add_hrv_ms_to_bitacora'),
        ('entrenos', '0051_evaluacionsemanalgym_informativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionprogramada',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('saltada_usuario', 'Saltada por usuario'), ('omitida_usuario', 'Omitida por ausencia planificada'), ('omitida_sistema', 'Omitida por sistema'), ('cancelada_lesion', 'Cancelada por lesión')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='AusenciaPlanificadaGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(db_index=True)),
                ('fin', models.DateField(db_index=True)),
                ('motivo', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('viaje', 'Viaje'), ('enfermedad', 'Enfermedad'), ('otro', 'Otro')], max_length=20)),
                ('nota', models.TextField(blank=True)),
                ('sesiones_afectadas', models.PositiveIntegerField(default=0)),
                ('sesiones_snapshot', models.JSONField(blank=True, default=list)),
                ('deuda_generada', models.PositiveIntegerField(default=0, editable=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('confirmada_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ausencias_planificadas_gym', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-inicio', '-id'],
            },
        ),
        migrations.AddField(
            model_name='sesionprogramada',
            name='ausencia_planificada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='entrenos.ausenciaplanificadagym'),
        ),
        migrations.AddIndex(
            model_name='ausenciaplanificadagym',
            index=models.Index(fields=['cliente', 'inicio', 'fin'], name='entrenos_au_cliente_869d07_idx'),
        ),
    ]
