# Generated by Django 5.2 on 2026-09-14 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0053_ausenciaplanificadagym_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenorealizado',
            name='estado_cierre',
            field=models.CharField(choices=[('completa', 'Completa'), ('parcial', 'Parcial')], db_index=True, default='completa', max_length=12),
        ),
        migrations.AddField(
            model_name='entrenorealizado',
            name='motivo_cierre',
            field=models.CharField(blank=True, choices=[('fatiga', 'Fatiga'), ('tiempo', 'Falta de tiempo'), ('molestia', 'Molestia'), ('equipo', 'Equipo no disponible'), ('otro', 'Otro')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sesionprogramada',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('parcial', 'Parcial'), ('saltada_usuario', 'Saltada por usuario'), ('omitida_usuario', 'Omitida por ausencia planificada'), ('omitida_sistema', 'Omitida por sistema'), ('cancelada_lesion', 'Cancelada por lesión')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='EjercicioOmitidoEntreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicio', models.CharField(max_length=200)),
                ('nombre_normalizado', models.CharField(max_length=120)),
                ('motivo', models.CharField(choices=[('fatiga', 'Fatiga'), ('tiempo', 'Falta de tiempo'), ('molestia', 'Molestia'), ('equipo', 'Equipo no disponible'), ('otro', 'Otro')], max_length=20)),
                ('es_principal', models.BooleanField(blank=True, null=True)),
                ('entreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_omitidos', to='entrenos.entrenorealizado')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('entreno', 'nombre_normalizado'), name='uniq_omitido_entreno_nombre_norm')],
            },
        ),
    ]
