# Generated by Django 5.2 on 2026-09-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0054_entrenorealizado_estado_cierre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serierealizada',
            name='distancia_metros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
