# Generated by Django 5.2 on 2026-09-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenos', '0057_alter_actividadrealizada_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='serierealizada',
            name='es_aproximacion',
            field=models.BooleanField(default=False, help_text='Serie preparatoria conservada en el historial, excluida de volumen, RPE agregado, 1RM y decisiones de progresión.'),
        ),
    ]
