# Generated by Django 5.2 on 2026-07-11 19:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0009_add_hrv_ms_to_bitacora'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('nivel', models.CharField(choices=[('A', 'Completa'), ('B', 'Suficiente'), ('C', 'Recurso')], max_length=1)),
                ('origen', models.CharField(blank=True, max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_disponibilidad', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
