# Generated by Django 5.2 on 2026-07-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodisponibilidad',
            name='momento_ingesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
